import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'eng/eng--architecture',
        'eng/eng--platform',
        'eng/eng--product',
        'eng/eng--experience',
        'eng/eng--quality-migration',
        { type: 'autogenerated', dirName: 'eng/runbooks' },
      ],
    },
    {
      type: 'category',
      label: 'ADRs',
      items: [{ type: 'autogenerated', dirName: 'eng/decisions' }],
    },
    {
      type: 'category',
      label: 'Contracts',
      items: [
        { type: 'autogenerated', dirName: 'eng/api' },
        { type: 'autogenerated', dirName: 'eng/domains' },
        { type: 'autogenerated', dirName: 'eng/facts' },
      ],
    },
    {
      type: 'category',
      label: 'Engineering',
      items: [
        { type: 'autogenerated', dirName: 'eng' },
        { type: 'autogenerated', dirName: 'eng/Banking' },
      ],
    },
    {
      type: 'category',
      label: 'Governance',
      items: [
        'gov/gov--index',
        { type: 'autogenerated', dirName: 'gov/audit' },
        { type: 'autogenerated', dirName: 'gov/evidence' },
        { type: 'autogenerated', dirName: 'gov/compliance' },
        { type: 'autogenerated', dirName: 'gov/health' },
        { type: 'autogenerated', dirName: 'gov/prompts' },
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [{ type: 'autogenerated', dirName: 'ops' }],
    },
    {
      type: 'category',
      label: 'Schemas',
      items: [
        { type: 'autogenerated', dirName: 'refs/esocial' },
        { type: 'autogenerated', dirName: 'refs/tce' },
      ],
    },
    {
      type: 'category',
      label: 'User',
      items: [{ type: 'autogenerated', dirName: 'user' }],
    },
    {
      type: 'category',
      label: 'Legacy',
      items: [{ type: 'autogenerated', dirName: 'leg' }],
    },
    {
      type: 'category',
      label: 'References',
      items: [
        { type: 'autogenerated', dirName: 'refs/legal' },
        { type: 'autogenerated', dirName: 'refs/lgpd' },
      ],
    },
  ],
};

export default sidebars;
