#!/usr/bin/env node

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { parseArgs } from '../cli.mjs';
import { defaultRepoRoot } from '../repo-paths.mjs';

const usage = `
Usage: node scripts/generate.mjs permissions [--help]

Generate backend and frontend permission catalogs from database/seed/permission-catalog.json.
`;

const options = parseArgs(process.argv.slice(2), { booleanFlags: ['help'] });
if (options.help) {
  console.log(usage.trim());
  process.exit(0);
}

const seedPath = resolve(defaultRepoRoot, 'database/seed/permission-catalog.json');
const backendCatalogPath = resolve(
  defaultRepoRoot,
  'backend/src/iam/permissions/permission-catalog.generated.ts',
);
const frontendCatalogPath = resolve(
  defaultRepoRoot,
  'frontend/src/app/core/navigation/route-permission-map.generated.ts',
);

function readSeed() {
  const parsed = JSON.parse(readFileSync(seedPath, 'utf8'));
  const permissions = Array.isArray(parsed.permissions) ? parsed.permissions : [];
  const codes = permissions.map((permission) => permission.key);
  const unique = new Set(codes);
  if (codes.length === 0) {
    throw new Error('permission-catalog.json must contain at least one permission');
  }
  if (unique.size !== codes.length) {
    throw new Error('permission-catalog.json contains duplicate keys');
  }
  const tuples = permissions.map(
    (permission) => `${permission.moduleKey}:${permission.resourceKey}:${permission.actionKey}`,
  );
  const uniqueTuples = new Set(tuples);
  if (uniqueTuples.size !== tuples.length) {
    throw new Error('permission-catalog.json contains duplicate module/resource/action tuples');
  }
  return { permissions };
}

function writeBackendCatalog(seed) {
  const permissions = seed.permissions.map((permission) => permission.key).sort();
  const permissionLines = permissions.map((permission) => `  '${permission}',`).join('\n');
  const content = `// Generated by scripts/generate.mjs permissions. Do not edit by hand.
export const PERMISSIONS = [
${permissionLines}
] as const;

export type Permission = (typeof PERMISSIONS)[number];
`;
  writeFileSync(backendCatalogPath, content);
}

function writeFrontendCatalog(seed) {
  const entries = seed.permissions
    .filter((permission) => permission.routePattern?.startsWith('#!'))
    .map((permission) => [permission.routePattern ?? '', permission.key])
    .sort((left, right) => left[0].localeCompare(right[0]));
  const entryLines = entries
    .map(([pattern, permission]) => `  ['${pattern}', '${permission}'],`)
    .join('\n');
  const content = `// Generated by scripts/generate.mjs permissions. Do not edit by hand.
export const ROUTE_PERMISSION_MAP = [
${entryLines}
] as const;

export function permissionsForRoutePath(routePath: string): string[] {
  return ROUTE_PERMISSION_MAP.filter(([pattern]) => routeMatches(pattern, routePath)).map(
    ([, permission]) => permission,
  );
}

function routeMatches(pattern: string, routePath: string): boolean {
  const normalizedPattern = pattern.replace(/^#!/, '').replace(/\\/\\*\\*$/, '');
  const normalizedRoute = routePath.replace(/^#!/, '');
  return normalizedRoute.startsWith(normalizedPattern);
}
`;
  writeFileSync(frontendCatalogPath, content);
}

const seed = readSeed();
writeBackendCatalog(seed);
writeFrontendCatalog(seed);
