CREATE SCHEMA IF NOT EXISTS avaliacao;

CREATE SCHEMA IF NOT EXISTS esocial;

CREATE SCHEMA IF NOT EXISTS fiscal;

CREATE SCHEMA IF NOT EXISTS hr;

CREATE SCHEMA IF NOT EXISTS lgpd;

CREATE SCHEMA IF NOT EXISTS payment;

CREATE SCHEMA IF NOT EXISTS payroll;

CREATE SCHEMA IF NOT EXISTS payroll_calc;

CREATE SCHEMA IF NOT EXISTS ponto;

CREATE SCHEMA IF NOT EXISTS portal;

CREATE SCHEMA IF NOT EXISTS postgis;

CREATE SCHEMA IF NOT EXISTS public;

CREATE SCHEMA IF NOT EXISTS public_data;

CREATE SCHEMA IF NOT EXISTS recrutamento;

CREATE SCHEMA IF NOT EXISTS saude;

CREATE SCHEMA IF NOT EXISTS tce;
