-- Generated by scripts/check-db.mjs fk-coverage write.
-- Promoted inferred foreign keys require a clean live orphan report before validation.

ALTER TABLE ONLY hr.merit_progression
    ADD CONSTRAINT merit_progression_administrative_process_id_inferred_fkey
    FOREIGN KEY (administrative_process_id) REFERENCES hr.administrative_process(id);
