-- Generated by scripts/check-db-fk-coverage.mjs --write.
-- Conservative inferred foreign keys are NOT VALID until orphan reports are clean.

ALTER TABLE ONLY esocial.s2299_pending
    ADD CONSTRAINT s2299_pending_employee_id_inferred_fkey
    FOREIGN KEY (employee_id) REFERENCES hr.employee(id) ON DELETE CASCADE NOT VALID;

ALTER TABLE ONLY esocial.s2299_pending
    ADD CONSTRAINT s2299_pending_employment_link_id_inferred_fkey
    FOREIGN KEY (employment_link_id) REFERENCES hr.employment_link(id) ON DELETE CASCADE NOT VALID;

ALTER TABLE ONLY hr.merit_progression
    ADD CONSTRAINT merit_progression_administrative_process_id_inferred_fkey
    FOREIGN KEY (administrative_process_id) REFERENCES hr.administrative_process(id) NOT VALID;

ALTER TABLE ONLY public.esocial_event
    ADD CONSTRAINT esocial_event_payroll_run_id_inferred_fkey
    FOREIGN KEY (payroll_run_id) REFERENCES payroll.payroll_run(id) ON DELETE SET NULL NOT VALID;
