-- Generated by scripts/check-db.mjs fk-coverage write.
-- Promoted inferred foreign keys require a clean live orphan report before validation.

ALTER TABLE ONLY esocial.s2299_pending
    ADD CONSTRAINT s2299_pending_employee_id_inferred_fkey
    FOREIGN KEY (employee_id) REFERENCES hr.employee(id) ON DELETE CASCADE;

ALTER TABLE ONLY esocial.s2299_pending
    ADD CONSTRAINT s2299_pending_employment_link_id_inferred_fkey
    FOREIGN KEY (employment_link_id) REFERENCES hr.employment_link(id) ON DELETE CASCADE;

ALTER TABLE ONLY hr.merit_progression
    ADD CONSTRAINT merit_progression_administrative_process_id_inferred_fkey
    FOREIGN KEY (administrative_process_id) REFERENCES hr.administrative_process(id);

ALTER TABLE ONLY public.esocial_event
    ADD CONSTRAINT esocial_event_payroll_run_id_inferred_fkey
    FOREIGN KEY (payroll_run_id) REFERENCES payroll.payroll_run(id) ON DELETE SET NULL;
