export const PERMISSIONS = [
  'auth:read',
  'iam:read',
  'gestao:read',
  'gestao:write',
  'rh:read',
  'rh:write',
  'rh.employee.read',
  'rh.employee.write',
  'folha:read',
  'folha:write',
  'folha.calc.read',
  'folha.calc.write',
  'avaliacao:read',
  'avaliacao:write',
  'consultas:read',
  'previdenciario:read',
  'previdenciario:write',
  'recrutamento:read',
  'recrutamento:write',
  'saude:read',
  'saude:write',
  'convenio:read',
  'convenio:write',
  'relatorio:read',
  'relatorio:generate',
  'documents:upload',
  'documents:register',
  'documents:download',
  'auditoria:read',
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const GROUP_PERMISSION_MAP: Record<string, Permission[]> = {
  SGP_ADMIN: [...PERMISSIONS],
  ADMIN: [...PERMISSIONS],
  SGP_GESTAO: ['auth:read', 'gestao:read', 'gestao:write'],
  GESTAO: ['auth:read', 'gestao:read', 'gestao:write'],
  SGP_RH: [
    'auth:read',
    'rh:read',
    'rh:write',
    'rh.employee.read',
    'rh.employee.write',
    'gestao:read',
  ],
  RH: [
    'auth:read',
    'rh:read',
    'rh:write',
    'rh.employee.read',
    'rh.employee.write',
    'gestao:read',
  ],
  SGP_FOLHA: [
    'auth:read',
    'folha:read',
    'folha:write',
    'folha.calc.read',
    'folha.calc.write',
    'rh:read',
  ],
  FOLHA: [
    'auth:read',
    'folha:read',
    'folha:write',
    'folha.calc.read',
    'folha.calc.write',
    'rh:read',
  ],
  SGP_AVALIACAO: [
    'auth:read',
    'avaliacao:read',
    'avaliacao:write',
    'rh:read',
    'gestao:read',
  ],
  AVALIACAO: [
    'auth:read',
    'avaliacao:read',
    'avaliacao:write',
    'rh:read',
    'gestao:read',
  ],
  SGP_CONSULTAS: [
    'auth:read',
    'consultas:read',
    'rh:read',
    'folha:read',
    'relatorio:read',
  ],
  CONSULTAS: [
    'auth:read',
    'consultas:read',
    'rh:read',
    'folha:read',
    'relatorio:read',
  ],
  SGP_PREVIDENCIARIO: [
    'auth:read',
    'previdenciario:read',
    'previdenciario:write',
    'rh:read',
    'gestao:read',
    'relatorio:read',
    'relatorio:generate',
  ],
  PREVIDENCIARIO: [
    'auth:read',
    'previdenciario:read',
    'previdenciario:write',
    'rh:read',
    'gestao:read',
    'relatorio:read',
    'relatorio:generate',
  ],
  SGP_RECRUTAMENTO: [
    'auth:read',
    'recrutamento:read',
    'recrutamento:write',
    'rh:read',
  ],
  RECRUTAMENTO: [
    'auth:read',
    'recrutamento:read',
    'recrutamento:write',
    'rh:read',
  ],
  SGP_SAUDE: ['auth:read', 'saude:read', 'saude:write', 'rh:read'],
  SAUDE: ['auth:read', 'saude:read', 'saude:write', 'rh:read'],
  SGP_CONVENIO: ['auth:read', 'convenio:read', 'convenio:write'],
  CONVENIO: ['auth:read', 'convenio:read', 'convenio:write'],
  SGP_RELATORIO: [
    'auth:read',
    'relatorio:read',
    'relatorio:generate',
    'documents:upload',
    'documents:register',
    'documents:download',
  ],
  RELATORIO: [
    'auth:read',
    'relatorio:read',
    'relatorio:generate',
    'documents:upload',
    'documents:register',
    'documents:download',
  ],
  SGP_AUDITORIA: ['auth:read', 'auditoria:read'],
  AUDITORIA: ['auth:read', 'auditoria:read'],
};
