import { NotFoundException, ServiceUnavailableException } from '@nestjs/common';
import { QueryResultRow } from 'pg';

import { DatabaseService } from '../database/database.service';
import {
  ExternalLifeProofChannelInput,
  PensionCompensationStatusInput,
  RecertificationStatusInput,
  RecertificationTypeInput,
} from './previdenciario.dto';
import {
  BeneficiaryContactHistoryRow,
  ContributionTimeCertificateRow,
  EmployeeRetirementRow,
  ExternalLifeProofRow,
  PensionCompensationRow,
  PensionGrantRow,
  PrevidentiaryDeclarationRow,
  RecertificationBeneficiaryRow,
  RecertificationCampaignRow,
  RecertificationRecordRow,
  ReportRequestRow,
  RetirementGrantRow,
  RetirementRuleRow,
  RetirementSimulationRow,
} from './previdenciario.types';

export function ensureDatabase(databaseService: DatabaseService): void {
  if (!databaseService.configured) {
    throw new ServiceUnavailableException('DATABASE_URL is not configured');
  }
}

export async function employeeRow(
  databaseService: DatabaseService,
  id: string,
): Promise<EmployeeRetirementRow> {
  const rows = await databaseService.query<EmployeeRetirementRow>(
    `
    SELECT id, registration, name, birth_date, hired_on, cpf
    FROM hr.employee
    WHERE id = $1::uuid
    `,
    [id],
  );
  if (!rows[0]) {
    throw new NotFoundException('Employee not found');
  }
  return rows[0];
}

export async function ruleRow(
  databaseService: DatabaseService,
  id: string,
): Promise<RetirementRuleRow> {
  const rows = await databaseService.query<RetirementRuleRow>(
    `
    SELECT
      id,
      name,
      legal_basis,
      age_criteria,
      contribution_time_criteria,
      grace_period_criteria,
      applicable_employment_link,
      active
    FROM hr.retirement_rule
    WHERE id = $1::uuid
    `,
    [id],
  );
  if (!rows[0]) {
    throw new NotFoundException('Retirement rule not found');
  }
  return rows[0];
}

export async function beneficiaryRow(
  databaseService: DatabaseService,
  id: string,
) {
  const rows = await databaseService.query<QueryResultRow>(
    `SELECT id FROM hr.recertification_beneficiary WHERE id = $1::uuid`,
    [id],
  );
  if (!rows[0]) {
    throw new NotFoundException('Recertification beneficiary not found');
  }
}

export async function createReportRequest(
  databaseService: DatabaseService,
  code: string,
  name: string,
  parameters: Record<string, unknown>,
) {
  const definitionId = await ensureDefinition(
    databaseService,
    code,
    name,
    `GENERATE request generated by previdenciario runtime for ${code}`,
  );
  const rows = await databaseService.query<ReportRequestRow>(
    `
    INSERT INTO public.report_request (
      definition_id,
      status,
      parameters
    )
    VALUES (
      $1::uuid,
      'REQUESTED'::"ReportRequestStatus",
      $2::jsonb
    )
    RETURNING id, status::text AS status, requested_at
    `,
    [definitionId, JSON.stringify(parameters)],
  );
  return {
    id: rows[0]?.id ?? '',
    status: rows[0]?.status ?? 'REQUESTED',
    requestedAt: toIso(rows[0]?.requested_at ?? new Date()),
  };
}

async function ensureDefinition(
  databaseService: DatabaseService,
  code: string,
  name: string,
  description: string,
): Promise<string> {
  const rows = await databaseService.query<{ id: string } & QueryResultRow>(
    `
    WITH inserted AS (
      INSERT INTO public.report_definition (
        tenant_id,
        code,
        name,
        description,
        module_key,
        status
      )
      SELECT
        public.sgp_current_tenant_uuid(),
        $1,
        $2,
        $3,
        'previdenciario',
        'ACTIVE'::"RecordStatus"
      WHERE NOT EXISTS (
        SELECT 1
        FROM public.report_definition
        WHERE code = $1
          AND tenant_id = public.sgp_current_tenant_uuid()
      )
      RETURNING id::text
    )
    SELECT id::text FROM inserted
    UNION ALL
    SELECT id::text
    FROM public.report_definition
    WHERE code = $1
      AND tenant_id = public.sgp_current_tenant_uuid()
    LIMIT 1
    `,
    [code, name, description],
  );
  return rows[0]?.id ?? '';
}

export function toRuleSummary(row: RetirementRuleRow) {
  return {
    id: row.id,
    nome: row.name,
    fundamentoLegal: row.legal_basis,
    criteriosIdade: asObject(row.age_criteria),
    criteriosTempoContribuicao: asObject(row.contribution_time_criteria),
    criteriosCarencia: asObject(row.grace_period_criteria),
    vinculoAplicavel: row.applicable_employment_link,
    ativa: row.active,
  };
}

export function toSimulationSummary(row: RetirementSimulationRow) {
  return {
    id: row.id,
    funcionarioId: row.employee_id,
    matricula: row.registration,
    nome: row.employee_name,
    regraId: row.rule_id,
    regra: row.rule_name,
    resultado: asObject(row.result),
    detalheJson: asObject(row.details_json),
    simuladaEm: toIso(row.simulated_on),
    criadaPor: row.created_by_ref,
  };
}

export function toGrantSummary(row: RetirementGrantRow) {
  return {
    id: row.id,
    funcionarioId: row.employee_id,
    matricula: row.registration,
    nome: row.employee_name,
    regraId: row.rule_id,
    regra: row.rule_name,
    dataConcessao: toIsoDate(row.granted_on),
    fundamento: row.legal_basis,
    atoNomeacao: row.appointment_act,
    status: row.status,
    observacao: row.notes,
    concedidaPor: row.granted_by_ref,
  };
}

export function toPensionSummary(row: PensionGrantRow) {
  return {
    id: row.id,
    funcionarioInstituidorId: row.instituting_employee_id,
    matriculaInstituidor: row.registration,
    nomeInstituidor: row.employee_name,
    nomeBeneficiario: row.beneficiary_name,
    cpfBeneficiario: row.beneficiary_cpf,
    parentesco: row.kinship,
    tipoBeneficio: row.benefit_type,
    tipoRateio: row.apportionment_type,
    cotaParte: Number(row.share_percent),
    formaReajuste: row.adjustment_mode,
    natureza: row.nature,
    dataConcessao: toIsoDate(row.granted_on),
    dataCessacao: row.ceased_on ? toIsoDate(row.ceased_on) : null,
    fundamento: row.legal_basis,
    observacao: row.notes,
  };
}

export function toContributionTimeCertificateSummary(
  row: ContributionTimeCertificateRow,
) {
  return {
    id: row.id,
    funcionarioId: row.employee_id,
    matricula: row.registration,
    nome: row.employee_name,
    periodoInicio: toIsoDate(row.period_start),
    periodoFim: toIsoDate(row.period_end),
    orgaoEmitente: row.issuing_agency,
    atoEmissao: row.issuance_act,
    storageKey: row.storage_key,
    emitidaEm: toIso(row.issued_at),
    emitidaPor: row.issued_by_ref,
  };
}

export function toDeclarationSummary(row: PrevidentiaryDeclarationRow) {
  return {
    id: row.id,
    funcionarioId: row.employee_id,
    matricula: row.registration,
    nome: row.employee_name,
    tipo: row.type,
    storageKey: row.storage_key,
    emitidaEm: toIso(row.issued_at),
    emitidaPor: row.issued_by_ref,
  };
}

export function toCompensationSummary(row: PensionCompensationRow) {
  return {
    id: row.id,
    funcionarioId: row.employee_id,
    matricula: row.registration,
    nome: row.employee_name,
    certidaoReferencia: row.certificate_ref,
    regimeOrigem: row.origin_regime,
    valor: Number(row.amount),
    status: toCompensationStatusInput(row.status),
    observacao: row.notes,
  };
}

export function toCampaignSummary(row: RecertificationCampaignRow) {
  return {
    id: row.id,
    tipo: toRecertificationTypeInput(row.type),
    cicloInicio: toIsoDate(row.cycle_start),
    cicloFim: toIsoDate(row.cycle_end),
    filtro: asObject(row.filter_json),
    ativa: row.active,
  };
}

export function toBeneficiarySummary(row: RecertificationBeneficiaryRow) {
  return {
    id: row.id,
    funcionarioId: row.employee_id,
    matricula: row.registration,
    nome: row.employee_name,
    campanhaId: row.campaign_id,
    tipo: toRecertificationTypeInput(row.type),
    dataProxima: toIsoDate(row.next_due_date),
    status: toRecertificationStatusInput(row.status),
  };
}

export function toRecordSummary(row: RecertificationRecordRow) {
  return {
    id: row.id,
    beneficiarioId: row.beneficiary_id,
    data: toIsoDate(row.recertified_on),
    operadorId: row.operator_ref,
    dadosSnapshot: asObject(row.snapshot_json),
    comprovanteStorageKey: row.receipt_storage_key,
  };
}

export function toLifeProofSummary(row: ExternalLifeProofRow) {
  return {
    id: row.id,
    beneficiarioId: row.beneficiary_id,
    canal: row.channel as ExternalLifeProofChannelInput,
    autenticacao: asObject(row.authentication_json),
    data: toIso(row.proven_at),
  };
}

export function toBeneficiaryContactHistorySummary(
  row: BeneficiaryContactHistoryRow,
) {
  return {
    id: row.id,
    beneficiarioId: row.beneficiary_id,
    funcionarioId: row.employee_id,
    matricula: row.registration,
    nome: row.employee_name,
    data: toIsoDate(row.contacted_on),
    usuarioId: row.user_ref,
    observacao: row.notes,
  };
}

export function toCompensationStatusDb(
  value: PensionCompensationStatusInput,
): string {
  switch (value) {
    case 'RASCUNHO':
      return 'DRAFT';
    case 'SOLICITADA':
      return 'REQUESTED';
    case 'APROVADA':
      return 'APPROVED';
    case 'REPROVADA':
      return 'REJECTED';
    case 'LIQUIDADA':
      return 'SETTLED';
  }
}

function toCompensationStatusInput(
  value: string,
): PensionCompensationStatusInput {
  switch (value) {
    case 'DRAFT':
      return 'RASCUNHO';
    case 'REQUESTED':
      return 'SOLICITADA';
    case 'APPROVED':
      return 'APROVADA';
    case 'REJECTED':
      return 'REPROVADA';
    case 'SETTLED':
    default:
      return 'LIQUIDADA';
  }
}

export function toRecertificationTypeDb(
  value: RecertificationTypeInput,
): string {
  switch (value) {
    case 'APOSENTADO':
      return 'RETIREE';
    case 'PENSIONISTA':
      return 'PENSIONER';
    case 'PENSIONISTA_UNIVERSITARIO':
      return 'UNIVERSITY_PENSIONER';
  }
}

function toRecertificationTypeInput(value: string): RecertificationTypeInput {
  switch (value) {
    case 'RETIREE':
      return 'APOSENTADO';
    case 'PENSIONER':
      return 'PENSIONISTA';
    case 'UNIVERSITY_PENSIONER':
    default:
      return 'PENSIONISTA_UNIVERSITARIO';
  }
}

export function toRecertificationStatusDb(
  value: RecertificationStatusInput,
): string {
  switch (value) {
    case 'PENDENTE':
      return 'PENDING';
    case 'RECADASTRADO':
      return 'RECERTIFIED';
    case 'PROXIMO_VENCIMENTO':
      return 'NEAR_DUE';
    case 'VENCIDO':
      return 'OVERDUE';
    case 'BLOQUEADO':
      return 'BLOCKED';
  }
}

function toRecertificationStatusInput(
  value: string,
): RecertificationStatusInput {
  switch (value) {
    case 'PENDING':
      return 'PENDENTE';
    case 'RECERTIFIED':
      return 'RECADASTRADO';
    case 'NEAR_DUE':
      return 'PROXIMO_VENCIMENTO';
    case 'OVERDUE':
      return 'VENCIDO';
    case 'BLOCKED':
    default:
      return 'BLOQUEADO';
  }
}

export function asObject(value: unknown): Record<string, unknown> {
  if (value && typeof value === 'object' && !Array.isArray(value)) {
    return value as Record<string, unknown>;
  }
  if (typeof value === 'string' && value.trim()) {
    return JSON.parse(value) as Record<string, unknown>;
  }
  return {};
}

export function numberish(value: unknown): number {
  const numeric = Number(value ?? 0);
  return Number.isFinite(numeric) ? numeric : 0;
}

export function diffYears(
  dateValue: Date | string | null,
  referenceDate: string,
): number {
  if (!dateValue) return 0;
  const source = new Date(dateValue);
  const reference = new Date(referenceDate);
  let years = reference.getUTCFullYear() - source.getUTCFullYear();
  const sourceMonth = source.getUTCMonth();
  const referenceMonth = reference.getUTCMonth();
  if (
    referenceMonth < sourceMonth ||
    (referenceMonth === sourceMonth &&
      reference.getUTCDate() < source.getUTCDate())
  ) {
    years -= 1;
  }
  return Math.max(0, years);
}

export function toIso(value: Date | string): string {
  return new Date(value).toISOString();
}

export function toIsoDate(value: Date | string): string {
  return toIso(value).slice(0, 10);
}
