import { permissionsForRoutePath } from './route-permission-map.generated';

export type AdminModuleKey =
  | 'gestao'
  | 'rh'
  | 'folha'
  | 'avaliacao'
  | 'recrutamento'
  | 'consultas'
  | 'relatorios'
  | 'previdenciario'
  | 'auditoria'
  | 'saude'
  | 'ponto'
  | 'convenio'
  | 'fiscal';

export type AdminFeatureMode = 'management' | 'form' | 'details' | 'dashboard';

export interface AdminFeature {
  id: string;
  label: string;
  moduleLabel: string;
  moduleKey: AdminModuleKey;
  sectionLabel: string;
  routePath: string;
  childPath: string;
  requiredRole: string;
  requiredPermissions: string[];
  featureFlag: string;
  backendModule: string;
  comment: string;
  mode: AdminFeatureMode;
}

export interface AdminNavigationSection {
  moduleLabel: string;
  moduleKey: AdminModuleKey;
  routePath: string;
  items: AdminFeature[];
}

interface FeatureEntry {
  readonly label: string;
  readonly moduleLabel: string;
  readonly moduleKey: AdminModuleKey;
  readonly sectionLabel: string;
  readonly routePath: string;
  readonly requiredRole: string;
  readonly featureFlag: string;
  readonly backendModule: string;
  readonly comment: string;
}

const ADMIN_FEATURE_CATALOG = [
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Área de Formação',
    routePath: '/gestao/area-formacao/gestao',
    requiredRole: 'AREA_FORMACAO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Cadastro mestre',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Atividade',
    routePath: '/gestao/atividade/gestao',
    requiredRole: 'ATIVIDADE.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Cadastro mestre',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Banco',
    routePath: '/gestao/banco/gestao',
    requiredRole: 'BANCO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Banco e agência',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Categoria Profissional',
    routePath: '/gestao/categoria-profissional/gestao',
    requiredRole: 'CATEGORIA_PROFISSIONAL.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'CBO',
    routePath: '/gestao/cbo/gestao',
    requiredRole: 'CBO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Classificação Brasileira de Ocupações',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'CNAE',
    routePath: '/gestao/cnae/gestao',
    requiredRole: 'CNAE.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Atividade econômica',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Centro de Custo',
    routePath: '/gestao/centro-custo/gestao',
    requiredRole: 'CENTRO_CUSTO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Consignado',
    routePath: '/gestao/consignado/gestao',
    requiredRole: 'CONSIGNADO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Entidade de desconto consignado',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Conta Contábil',
    routePath: '/gestao/conta-contabil/gestao',
    requiredRole: 'CONTA_CONTABIL.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Plano de contas simplificado e completo',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Convênio (mestre)',
    routePath: '/gestao/convenio/gestao',
    requiredRole: 'CONVENIO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Somente cadastro mestre; gestão operacional em 3.11',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Curso',
    routePath: '/gestao/curso/gestao',
    requiredRole: 'CURSO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Cursos de formação',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Grau Acadêmico',
    routePath: '/gestao/grau-academico/gestao',
    requiredRole: 'GRAU_ACADEMICO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Município',
    routePath: '/gestao/municipio/gestao',
    requiredRole: 'MUNICIPIO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Tabela IBGE',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Nacionalidade / País',
    routePath: '/gestao/nacionalidade/gestao',
    requiredRole: 'NACIONALIDADE.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Sindicato',
    routePath: '/gestao/sindicato/gestao',
    requiredRole: 'SINDICATO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Turno',
    routePath: '/gestao/turno/gestao',
    requiredRole: 'TURNO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'UF',
    routePath: '/gestao/uf/gestao',
    requiredRole: 'UF.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Unidades Federativas',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Tipo de Documento',
    routePath: '/gestao/tipo-documento/gestao',
    requiredRole: 'TIPO_DOCUMENTO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Tipos de documentos pessoais',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Modelo de Documento',
    routePath: '/gestao/modelo-documento/gestao',
    requiredRole: 'MODELO_DOCUMENTO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Templates para geração de PDF',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Parâmetro Sistema',
    routePath: '/gestao/parametro-sistema/formulario',
    requiredRole: 'PARAMETRO_SISTEMA.GESTAO',
    featureFlag: '',
    backendModule: 'parametros',
    comment: 'Identidade do tenant; formulário único',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Parâmetro Global',
    routePath: '/gestao/parametro-global/gestao',
    requiredRole: 'PARAMETRO_GLOBAL.GESTAO',
    featureFlag: '',
    backendModule: 'parametros',
    comment: 'Chaves operacionais (teto, salário mínimo…)',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Teto Remuneratório',
    routePath: '/gestao/parametros/teto-remuneratorio',
    requiredRole: 'TETO_REMUNERATORIO.GESTAO',
    featureFlag: '',
    backendModule: 'parametros',
    comment: 'Subtetos por cargo/poder e parcelas imunes',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'ATS e Sexta-Parte',
    routePath: '/gestao/parametros/ats',
    requiredRole: 'ATS_PARAMETROS.GESTAO',
    featureFlag: '',
    backendModule: 'parametros',
    comment: 'Percentuais de ATS, triênio, quinquênio e sexta-parte',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Parametrizações',
    label: 'Feature Flag',
    routePath: '/gestao/feature-flag/gestao',
    requiredRole: 'FEATURE_FLAG.GESTAO',
    featureFlag: '',
    backendModule: 'parametros',
    comment: 'Ativação/desativação de funcionalidades',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Estrutura de Pessoal',
    label: 'Cargo',
    routePath: '/gestao/cargo/gestao',
    requiredRole: 'CARGO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Estrutura de Pessoal',
    label: 'Função',
    routePath: '/gestao/funcao/gestao',
    requiredRole: 'FUNCAO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Função comissionada ou de confiança',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Estrutura de Pessoal',
    label: 'Faixa Salarial',
    routePath: '/gestao/faixa-salarial/gestao',
    requiredRole: 'FAIXA_SALARIAL.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Estrutura de Pessoal',
    label: 'Referência Salarial',
    routePath: '/gestao/referencia-salarial/gestao',
    requiredRole: 'REFERENCIA_SALARIAL.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Estrutura de Pessoal',
    label: 'Lotação',
    routePath: '/gestao/lotacao/gestao',
    requiredRole: 'LOTACAO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Unidade administrativa',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Estrutura de Pessoal',
    label: 'Empresa Filial',
    routePath: '/gestao/empresa-filial/gestao',
    requiredRole: 'EMPRESA_FILIAL.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Filial do tenant',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Estrutura de Pessoal',
    label: 'Nível Salarial',
    routePath: '/gestao/nivel-salarial/gestao',
    requiredRole: 'NIVEL_SALARIAL.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Estrutura de Pessoal',
    label: 'Grupo Salarial',
    routePath: '/gestao/grupo-salarial/gestao',
    requiredRole: 'GRUPO_SALARIAL.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Estrutura de Pessoal',
    label: 'Vínculo',
    routePath: '/gestao/vinculo/gestao',
    requiredRole: 'VINCULO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Tipos de vínculo (efetivo, comissionado…)',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Estrutura de Pessoal',
    label: 'Tipo de Contrato',
    routePath: '/gestao/tipo-contrato/gestao',
    requiredRole: 'TIPO_CONTRATO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Estrutura de Pessoal',
    label: 'Tipo de Folha',
    routePath: '/gestao/tipo-folha/gestao',
    requiredRole: 'TIPO_FOLHA.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Estrutura de Pessoal',
    label: 'Tipo de Ferias',
    routePath: '/gestao/tipo-ferias/gestao',
    requiredRole: 'TIPO_FERIAS.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Cadastro mestre de tipos de ferias',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Estrutura de Pessoal',
    label: 'Tipo de Processamento',
    routePath: '/gestao/tipo-processamento/gestao',
    requiredRole: 'TIPO_PROCESSAMENTO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'MENSAL, 13º, FÉRIAS…',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Estrutura de Pessoal',
    label: 'Verba / Rubrica',
    routePath: '/gestao/verba/gestao',
    requiredRole: 'VERBA.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: 'Cadastro de verbas e fórmulas DSL',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Estrutura de Pessoal',
    label: 'Evento',
    routePath: '/gestao/evento/gestao',
    requiredRole: 'EVENTO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Eventos de eSocial',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Estrutura de Pessoal',
    label: 'Requisito',
    routePath: '/gestao/requisito/gestao',
    requiredRole: 'REQUISITO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Requisitos de cargos/funções',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Legais',
    label: 'Classificação de Atos',
    routePath: '/gestao/classificacao-ato/gestao',
    requiredRole: 'CLASSIFICACAO_ATO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Legais',
    label: 'Legislação / Motivo',
    routePath: '/gestao/motivo/gestao',
    requiredRole: 'MOTIVO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: 'Motivos gerais',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Legais',
    label: 'Tipo de Desligamento',
    routePath: '/gestao/tipo-desligamento/gestao',
    requiredRole: 'TIPO_DESLIGAMENTO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Legais',
    label: 'Causa de Afastamento',
    routePath: '/gestao/causa-afastamento/gestao',
    requiredRole: 'CAUSA_AFASTAMENTO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Legais',
    label: 'Motivo de Afastamento',
    routePath: '/gestao/motivo-afastamento/gestao',
    requiredRole: 'MOTIVO_AFASTAMENTO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Legais',
    label: 'Tipo de Averbação',
    routePath: '/gestao/tipo-averbacao/gestao',
    requiredRole: 'TIPO_AVERBACAO.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Gestão',
    moduleKey: 'gestao',
    sectionLabel: 'Legais',
    label: 'Tipo de Aposentadoria',
    routePath: '/gestao/tipo-aposentadoria/gestao',
    requiredRole: 'TIPO_APOSENTADORIA.GESTAO',
    featureFlag: '',
    backendModule: 'gestao',
    comment: '',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Cadastro Funcional',
    label: 'Servidor (Funcionário) — lista',
    routePath: '/rh/servidor/gestao',
    requiredRole: 'FUNCIONARIO.VISUALIZAR',
    featureFlag: '',
    backendModule: 'rh',
    comment: 'Usa termo_funcionario como label',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Cadastro Funcional',
    label: 'Servidor — novo',
    routePath: '/rh/servidor/formulario',
    requiredRole: 'FUNCIONARIO.CADASTRAR',
    featureFlag: '',
    backendModule: 'rh',
    comment: 'CPF obrigatório; validação de unicidade',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Cadastro Funcional',
    label: 'Servidor — editar',
    routePath: '/rh/servidor/formulario/:id',
    requiredRole: 'FUNCIONARIO.ATUALIZAR',
    featureFlag: '',
    backendModule: 'rh',
    comment: '',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Cadastro Funcional',
    label: 'Servidor — detalhes',
    routePath: '/rh/servidor/detalhes/:id',
    requiredRole: 'FUNCIONARIO.VISUALIZAR',
    featureFlag: '',
    backendModule: 'rh',
    comment: '',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Cadastro Funcional',
    label: 'Dado Complementar',
    routePath: '/rh/dado-complementar/gestao',
    requiredRole: 'DADO_COMPLEMENTAR.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: 'Campos adicionais por tenant',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Cadastro Funcional',
    label: 'Dependente',
    routePath: '/rh/dependente/gestao',
    requiredRole: 'DEPENDENTE.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: 'IR, Salário-Família, Pensão, Saúde',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Cadastro Funcional',
    label: 'Dependente Benefício',
    routePath: '/rh/dependente-beneficio/gestao',
    requiredRole: 'DEPENDENTE_BENEFICIO.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: 'Dependentes de plano de saúde/convênio',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Cadastro Funcional',
    label: 'Tempo de Serviço',
    routePath: '/rh/tempo-servico/gestao',
    requiredRole: 'TEMPO_SERVICO.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: 'Averbação de tempo anterior',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Cadastro Funcional',
    label: 'Experiência Profissional',
    routePath: '/rh/experiencia-profissional/gestao',
    requiredRole: 'EXPERIENCIA_PROFISSIONAL.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: '',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Cadastro Funcional',
    label: 'Dossiê / Observação Documental',
    routePath: '/rh/dossie/gestao',
    requiredRole: 'DOSSIE.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: 'Documentos e observações por servidor',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Cadastro Funcional',
    label: 'Documento de Amparo',
    routePath: '/rh/documento-amparo/gestao',
    requiredRole: 'DOCUMENTO_AMPARO.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: 'Obrigatório em cedência',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Vida Funcional',
    label: 'Posse — Efetivo',
    routePath: '/rh/posse-efetivo/gestao',
    requiredRole: 'POSSE_EFETIVO.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: 'Ingresso efetivo; gera termo de posse PDF',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Vida Funcional',
    label: 'Posse — Efetivo (formulário)',
    routePath: '/rh/posse-efetivo/formulario/:id',
    requiredRole: 'POSSE_EFETIVO.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: '',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Vida Funcional',
    label: 'Posse — Comissionado',
    routePath: '/rh/posse-comissionado/gestao',
    requiredRole: 'POSSE_COMISSIONADO.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: '',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Vida Funcional',
    label: 'Posse — Comissionado (formulário)',
    routePath: '/rh/posse-comissionado/formulario/:id',
    requiredRole: 'POSSE_COMISSIONADO.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: '',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Vida Funcional',
    label: 'Posse — Contratado',
    routePath: '/rh/posse-contratado/gestao',
    requiredRole: 'POSSE_CONTRATADO.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: '',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Vida Funcional',
    label: 'Posse — Contratado (formulário)',
    routePath: '/rh/posse-contratado/formulario/:id',
    requiredRole: 'POSSE_CONTRATADO.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: '',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Vida Funcional',
    label: 'Histórico de Situação',
    routePath: '/rh/historico-situacao/gestao',
    requiredRole: 'HISTORICO_SITUACAO_FUNCIONAL.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: '',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Vida Funcional',
    label: 'Afastamento',
    routePath: '/rh/afastamento/gestao',
    requiredRole: 'AFASTAMENTO.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: 'Valida limite anual por motivo',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Vida Funcional',
    label: 'Transferência',
    routePath: '/rh/transferencia/gestao',
    requiredRole: 'TRANSFERENCIA.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: 'Com ou sem ônus; designada',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Vida Funcional',
    label: 'Exoneração / Desligamento',
    routePath: '/rh/desligamento/gestao',
    requiredRole: 'DESLIGAMENTO.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: '',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Vida Funcional',
    label: 'Rescisão de Contrato',
    routePath: '/rh/rescisao/gestao',
    requiredRole: 'RESCISAO.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: 'Contratados CLT/temporários',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Vida Funcional',
    label: 'Falta',
    routePath: '/rh/falta/gestao',
    requiredRole: 'FALTA.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: '',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Vida Funcional',
    label: 'Frequência',
    routePath: '/rh/frequencia/gestao',
    requiredRole: 'FREQUENCIA.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: 'Registro de frequência',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Vida Funcional',
    label: 'Programação de Férias',
    routePath: '/rh/ferias-programacao/gestao',
    requiredRole: 'FERIAS.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: 'Agendamento de férias',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Vida Funcional',
    label: 'Licença-Prêmio',
    routePath: '/rh/licenca-premio/gestao',
    requiredRole: 'LICENCA_PREMIO.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: '',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Vida Funcional',
    label: 'Progressão Salarial',
    routePath: '/rh/nivel-salarial-historico/gestao',
    requiredRole: 'PROGRESSAO_SALARIAL.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: 'Histórico de nível/referência',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Correlatos',
    label: 'Pensão Alimentícia',
    routePath: '/rh/pensao-alimenticia/gestao',
    requiredRole: 'PENSAO_ALIMENTICIA.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: '',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Correlatos',
    label: 'Contribuição Sindical',
    routePath: '/rh/contribuicao-sindical/gestao',
    requiredRole: 'CONTRIBUICAO_SINDICAL.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: '',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Correlatos',
    label: 'Decisão Judicial',
    routePath: '/rh/decisao-judicial/gestao',
    requiredRole: 'DECISAO_JUDICIAL.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: '',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Correlatos',
    label: 'Categoria Profissional (vínculo)',
    routePath: '/rh/categoria-profissional-vinculo/gestao',
    requiredRole: 'CATEGORIA_PROFISSIONAL.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: 'Associação servidor × categoria',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Correlatos',
    label: 'Processo',
    routePath: '/rh/processo/gestao',
    requiredRole: 'PROCESSO.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: 'Processos administrativos',
  },
  {
    moduleLabel: 'Módulo RH',
    moduleKey: 'rh',
    sectionLabel: 'Correlatos',
    label: 'Processo-Função',
    routePath: '/rh/processo-funcao/gestao',
    requiredRole: 'PROCESSO_FUNCAO.GESTAO',
    featureFlag: '',
    backendModule: 'rh',
    comment: 'Relação processo × função',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Centrais',
    label: 'Competência',
    routePath: '/folha/competencia/gestao',
    requiredRole: 'FOLHA_DE_PGT.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: 'Abertura, programação e fechamento',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Centrais',
    label: 'Folha de Pagamento',
    routePath: '/folha/folha-pagamento/gestao',
    requiredRole: 'FOLHA_DE_PGT.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: 'Por filial × tipo_processamento',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Centrais',
    label: 'Simulação',
    routePath: '/folha/simulacao',
    requiredRole: 'FOLHA_DE_PGT.SIMULACAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: 'What-if com rollback obrigatório',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Centrais',
    label: 'Contracheque — lista',
    routePath: '/folha/contracheque/gestao',
    requiredRole: 'FOLHA_DE_PGT.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: 'Listagem por competência',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Centrais',
    label: 'Contracheque — detalhes',
    routePath: '/folha/contracheque/detalhes/:id',
    requiredRole: 'FOLHA_DE_PGT.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: "Download PDF; marca d'água configurável",
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Verbas e Lançamentos',
    label: 'Verbas (cadastro)',
    routePath: '/folha/verba/gestao',
    requiredRole: 'VERBA.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: 'Fórmulas DSL; compilação SQL',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Verbas e Lançamentos',
    label: 'Verbas por Servidor',
    routePath: '/folha/verbas-servidor/gestao',
    requiredRole: 'VERBA_FUNCIONARIO.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: 'funcionario_verba',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Verbas e Lançamentos',
    label: 'Verbas por Pensionista',
    routePath: '/folha/verbas-pensionista/gestao',
    requiredRole: 'VERBA_PENSIONISTA.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: '',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Verbas e Lançamentos',
    label: 'Lançamento Manual',
    routePath: '/folha/lancamento-manual/gestao',
    requiredRole: 'LANCAMENTO_MANUAL.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: '',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Verbas e Lançamentos',
    label: 'Importador Verbas Servidor',
    routePath: '/folha/importacao-verbas-servidor/gestao',
    requiredRole: 'IMPORTACAO_VERBAS.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: 'Arquivo CSV/XLSX; substitutivo',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Verbas e Lançamentos',
    label: 'Importador Verbas Pensionista',
    routePath: '/folha/importacao-verbas-pensionista/gestao',
    requiredRole: 'IMPORTACAO_VERBAS.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: '',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Verbas e Lançamentos',
    label: 'Importação Consignado',
    routePath: '/folha/importacao-consignado/gestao',
    requiredRole: 'IMPORTACAO_CONSIGNADO.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: 'Leiaute Neoconsig',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Fechamentos e Obrigações',
    label: 'DIRF',
    routePath: '/folha/dirf/gestao',
    requiredRole: 'DIRF.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: 'Geração arquivo TXT RFB',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Fechamentos e Obrigações',
    label: 'SEFIP',
    routePath: '/folha/sefip/gestao',
    requiredRole: 'SEFIP.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: '',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Fechamentos e Obrigações',
    label: 'Remessa Bancária',
    routePath: '/folha/remessa-bancaria/gestao',
    requiredRole: 'ARQUIVO_REMESSA.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: 'CNAB 240/400 por banco',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Fechamentos e Obrigações',
    label: 'Retorno Bancário',
    routePath: '/folha/retorno-bancario/gestao',
    requiredRole: 'ARQUIVO_REMESSA.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: '',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Fechamentos e Obrigações',
    label: 'Batimento de Folha',
    routePath: '/folha/batimento/gestao',
    requiredRole: 'RELATORIO_BATIMENTO_FOLHA.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: 'Conferência de totais',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Relatórios de Folha',
    label: 'Relatório de Folha',
    routePath: '/folha/relatorio-folha/gestao',
    requiredRole: 'RELATORIO_FOLHA_PAGAMENTO.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: 'PDF/XLSX',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Relatórios de Folha',
    label: 'Relatório Financeiro',
    routePath: '/folha/relatorio-financeiro/gestao',
    requiredRole: 'RELATORIO_FOLHA_PAGAMENTO.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: 'Persiste relatorio_financeiro',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Relatórios de Folha',
    label: 'Proventos e Descontos',
    routePath: '/folha/relatorio-proventos-descontos/gestao',
    requiredRole: 'RELATORIO_PROVENTOS_DESCONTOS.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: '',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Relatórios de Folha',
    label: 'Repasse Fundo RH',
    routePath: '/folha/relatorio-repasse-fundo/gestao',
    requiredRole: 'RELATORIO_REPASSE_FUNDO_RH.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: '',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Relatórios de Folha',
    label: 'Relatório de Verbas',
    routePath: '/folha/relatorio-verbas/gestao',
    requiredRole: 'RELATORIO_VERBAS.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: '',
  },
  {
    moduleLabel: 'Folha de Pgt',
    moduleKey: 'folha',
    sectionLabel: 'Relatórios de Folha',
    label: 'Resumo de Folha',
    routePath: '/folha/resumo/gestao',
    requiredRole: 'RELATORIO_FOLHA_PAGAMENTO.GESTAO',
    featureFlag: '',
    backendModule: 'folha',
    comment: 'XLSX consolidado',
  },
  {
    moduleLabel: 'Módulo Avaliação',
    moduleKey: 'avaliacao',
    sectionLabel: '',
    label: 'Avaliação de Desempenho',
    routePath: '/avaliacao/avaliacao-desempenho/gestao',
    requiredRole: 'AVALIACAO_DESEMPENHO.GESTAO',
    featureFlag: '',
    backendModule: 'avaliacao',
    comment: 'Ciclos, critérios, notas',
  },
  {
    moduleLabel: 'Módulo Avaliação',
    moduleKey: 'avaliacao',
    sectionLabel: '',
    label: 'Progressão por Mérito',
    routePath: '/avaliacao/progressao-merito/gestao',
    requiredRole: 'PROGRESSAO_MERITO.GESTAO',
    featureFlag: '',
    backendModule: 'avaliacao',
    comment: '',
  },
  {
    moduleLabel: 'Módulo Avaliação',
    moduleKey: 'avaliacao',
    sectionLabel: '',
    label: 'Progressão por Titularidade',
    routePath: '/avaliacao/progressao-titularidade/gestao',
    requiredRole: 'PROGRESSAO_TITULARIDADE.GESTAO',
    featureFlag: '',
    backendModule: 'avaliacao',
    comment: '',
  },
  {
    moduleLabel: 'Módulo Avaliação',
    moduleKey: 'avaliacao',
    sectionLabel: '',
    label: 'Progressão Judicial',
    routePath: '/avaliacao/progressao-judicial/gestao',
    requiredRole: 'PROGRESSAO_JUDICIAL.GESTAO',
    featureFlag: '',
    backendModule: 'avaliacao',
    comment: 'Decisão judicial forçando progressão',
  },
  {
    moduleLabel: 'Módulo Avaliação',
    moduleKey: 'avaliacao',
    sectionLabel: '',
    label: 'Correção Salarial',
    routePath: '/avaliacao/correcao-salarial/gestao',
    requiredRole: 'CORRECAO_SALARIAL.GESTAO',
    featureFlag: '',
    backendModule: 'avaliacao',
    comment: 'Reajustes coletivos',
  },
  {
    moduleLabel: 'Módulo Avaliação',
    moduleKey: 'avaliacao',
    sectionLabel: '',
    label: 'Plano de Cargos e Carreira',
    routePath: '/avaliacao/plano-cargos-carreira/gestao',
    requiredRole: 'PLANO_CARGOS_CARREIRA.GESTAO',
    featureFlag: '',
    backendModule: 'avaliacao',
    comment: 'Versões e vigência',
  },
  {
    moduleLabel: 'Módulo Avaliação',
    moduleKey: 'avaliacao',
    sectionLabel: '',
    label: 'Simulador de Nível Salarial',
    routePath: '/avaliacao/simulador-nivel/gestao',
    requiredRole: 'SIMULADOR_NIVEL_SALARIAL.GESTAO',
    featureFlag: '',
    backendModule: 'avaliacao',
    comment: 'Cenário hipotético; não persiste alteração',
  },
  {
    moduleLabel: 'Recrutamento e Seleção',
    moduleKey: 'recrutamento',
    sectionLabel: 'Demanda',
    label: 'Requisição de Pessoal',
    routePath: '/recrutamento/requisicao-pessoal/gestao',
    requiredRole: 'REQUISICAO_DE_PESSOAL.GESTAO',
    featureFlag: '',
    backendModule: 'recrutamento',
    comment: 'Abertura e tramitação (RASCUNHO → EM_PROCESSO)',
  },
  {
    moduleLabel: 'Recrutamento e Seleção',
    moduleKey: 'recrutamento',
    sectionLabel: 'Demanda',
    label: 'Requisição — nova',
    routePath: '/recrutamento/requisicao-pessoal/formulario',
    requiredRole: 'REQUISICAO_DE_PESSOAL.CADASTRAR',
    featureFlag: '',
    backendModule: 'recrutamento',
    comment: 'Substitui colaborador ou aumento de quadro',
  },
  {
    moduleLabel: 'Recrutamento e Seleção',
    moduleKey: 'recrutamento',
    sectionLabel: 'Demanda',
    label: 'Requisição — editar',
    routePath: '/recrutamento/requisicao-pessoal/formulario/:id',
    requiredRole: 'REQUISICAO_DE_PESSOAL.ATUALIZAR',
    featureFlag: '',
    backendModule: 'recrutamento',
    comment: 'Só enquanto RASCUNHO',
  },
  {
    moduleLabel: 'Recrutamento e Seleção',
    moduleKey: 'recrutamento',
    sectionLabel: 'Demanda',
    label: 'Gestão de Requisições',
    routePath: '/recrutamento/gestao-requisicoes/gestao',
    requiredRole: 'REQUISICAO_DE_PESSOAL.GESTAO',
    featureFlag: '',
    backendModule: 'recrutamento',
    comment: 'Painel RH: APROVADO, REJEITADO, CONCLUIDO',
  },
  {
    moduleLabel: 'Recrutamento e Seleção',
    moduleKey: 'recrutamento',
    sectionLabel: 'Captação',
    label: 'Banco de Talentos',
    routePath: '/recrutamento/banco-talentos/gestao',
    requiredRole: 'BANCO_TALENTOS.GESTAO',
    featureFlag: '',
    backendModule: 'recrutamento',
    comment: 'Cadastros externos e internos',
  },
  {
    moduleLabel: 'Recrutamento e Seleção',
    moduleKey: 'recrutamento',
    sectionLabel: 'Captação',
    label: 'Cadastro de Currículo',
    routePath: '/recrutamento/curriculo/formulario',
    requiredRole: 'BANCO_TALENTOS.CADASTRAR',
    featureFlag: '',
    backendModule: 'recrutamento',
    comment: 'Upload S3',
  },
  {
    moduleLabel: 'Recrutamento e Seleção',
    moduleKey: 'recrutamento',
    sectionLabel: 'Captação',
    label: 'Currículo — editar',
    routePath: '/recrutamento/curriculo/formulario/:id',
    requiredRole: 'BANCO_TALENTOS.ATUALIZAR',
    featureFlag: '',
    backendModule: 'recrutamento',
    comment: '',
  },
  {
    moduleLabel: 'Recrutamento e Seleção',
    moduleKey: 'recrutamento',
    sectionLabel: 'Captação',
    label: 'Análise Curricular',
    routePath: '/recrutamento/analise-curricular/gestao',
    requiredRole: 'REQUISICAO_DE_PESSOAL.GESTAO',
    featureFlag: '',
    backendModule: 'recrutamento',
    comment: 'Candidatos por requisição',
  },
  {
    moduleLabel: 'Recrutamento e Seleção',
    moduleKey: 'recrutamento',
    sectionLabel: 'Estágio',
    label: 'Estagiário',
    routePath: '/recrutamento/estagiario/gestao',
    requiredRole: 'ESTAGIARIO.GESTAO',
    featureFlag: '',
    backendModule: 'recrutamento',
    comment: 'Lifecycle: ativo / encerrado',
  },
  {
    moduleLabel: 'Recrutamento e Seleção',
    moduleKey: 'recrutamento',
    sectionLabel: 'Estágio',
    label: 'Estagiário — novo',
    routePath: '/recrutamento/estagiario/formulario',
    requiredRole: 'ESTAGIARIO.CADASTRAR',
    featureFlag: '',
    backendModule: 'recrutamento',
    comment: 'Vincula programa e instituição',
  },
  {
    moduleLabel: 'Recrutamento e Seleção',
    moduleKey: 'recrutamento',
    sectionLabel: 'Estágio',
    label: 'Estagiário — editar',
    routePath: '/recrutamento/estagiario/formulario/:id',
    requiredRole: 'ESTAGIARIO.ATUALIZAR',
    featureFlag: '',
    backendModule: 'recrutamento',
    comment: '',
  },
  {
    moduleLabel: 'Recrutamento e Seleção',
    moduleKey: 'recrutamento',
    sectionLabel: 'Estágio',
    label: 'Programa de Estágio',
    routePath: '/recrutamento/programa-estagio/gestao',
    requiredRole: 'PROGRAMA_ESTAGIO.GESTAO',
    featureFlag: '',
    backendModule: 'recrutamento',
    comment: 'Vigência, bolsa, carga horária',
  },
  {
    moduleLabel: 'Recrutamento e Seleção',
    moduleKey: 'recrutamento',
    sectionLabel: 'Estágio',
    label: 'Prorrogação de Estágio',
    routePath: '/recrutamento/prorrogacao-estagio/gestao',
    requiredRole: 'PRORROGACAO_ESTAGIO.GESTAO',
    featureFlag: '',
    backendModule: 'recrutamento',
    comment: '',
  },
  {
    moduleLabel: 'Recrutamento e Seleção',
    moduleKey: 'recrutamento',
    sectionLabel: 'Estágio',
    label: 'Recesso de Estágio',
    routePath: '/recrutamento/recesso-estagio/gestao',
    requiredRole: 'RECESSO_ESTAGIO.GESTAO',
    featureFlag: '',
    backendModule: 'recrutamento',
    comment: 'Gera relatório próprio',
  },
  {
    moduleLabel: 'Consultas Gerenciais',
    moduleKey: 'consultas',
    sectionLabel: '',
    label: 'Ficha Financeira',
    routePath: '/consultas/ficha-financeira/gestao',
    requiredRole: 'FOLHA_DE_PGT.GESTAO',
    featureFlag: '',
    backendModule: 'consultas',
    comment: 'Histórico mensal por servidor',
  },
  {
    moduleLabel: 'Consultas Gerenciais',
    moduleKey: 'consultas',
    sectionLabel: '',
    label: 'Ficha Funcional',
    routePath: '/consultas/ficha-funcional/detalhes/:id',
    requiredRole: 'FUNCIONARIO.VISUALIZAR',
    featureFlag: '',
    backendModule: 'consultas',
    comment: 'View materializada ficha_funcional',
  },
  {
    moduleLabel: 'Consultas Gerenciais',
    moduleKey: 'consultas',
    sectionLabel: '',
    label: 'Relatórios por Situação',
    routePath: '/consultas/relatorio-situacao/gestao',
    requiredRole: 'RELATORIO_GERENCIAL.GESTAO',
    featureFlag: '',
    backendModule: 'consultas',
    comment: 'Filtragem por situação funcional',
  },
  {
    moduleLabel: 'Consultas Gerenciais',
    moduleKey: 'consultas',
    sectionLabel: '',
    label: 'Servidor com Pagamento Bloqueado',
    routePath: '/consultas/pagamento-bloqueado/gestao',
    requiredRole: 'RELATORIO_SERV_PAG_BLOQUEADO.GESTAO',
    featureFlag: '',
    backendModule: 'consultas',
    comment: 'Folha BLOQUEADO ou situação SUSTADO',
  },
  {
    moduleLabel: 'Consultas Gerenciais',
    moduleKey: 'consultas',
    sectionLabel: '',
    label: 'Histórico Operacional',
    routePath: '/consultas/historico-operacional/gestao',
    requiredRole: 'FUNCIONARIO.VISUALIZAR',
    featureFlag: '',
    backendModule: 'consultas',
    comment: 'Timeline de eventos do servidor',
  },
  {
    moduleLabel: 'Consultas Gerenciais',
    moduleKey: 'consultas',
    sectionLabel: '',
    label: 'Dashboard Geral',
    routePath: '/consultas/dashboard',
    requiredRole: 'RELATORIO_GERENCIAL.GESTAO',
    featureFlag: '',
    backendModule: 'consultas',
    comment: 'KPIs: efetivos, afastados, folha, etc.',
  },
  {
    moduleLabel: 'Relatório',
    moduleKey: 'relatorios',
    sectionLabel: '',
    label: 'Relatório Gerencial',
    routePath: '/relatorios/gerencial/gestao',
    requiredRole: 'RELATORIO_GERENCIAL.GESTAO',
    featureFlag: '',
    backendModule: 'relatorios',
    comment: 'PDF/XLSX por período',
  },
  {
    moduleLabel: 'Relatório',
    moduleKey: 'relatorios',
    sectionLabel: '',
    label: 'Relatório de Folha',
    routePath: '/relatorios/folha/gestao',
    requiredRole: 'RELATORIO_FOLHA_PAGAMENTO.GESTAO',
    featureFlag: '',
    backendModule: 'relatorios',
    comment: '',
  },
  {
    moduleLabel: 'Relatório',
    moduleKey: 'relatorios',
    sectionLabel: '',
    label: 'Relatório Financeiro',
    routePath: '/relatorios/financeiro/gestao',
    requiredRole: 'RELATORIO_FOLHA_PAGAMENTO.GESTAO',
    featureFlag: '',
    backendModule: 'relatorios',
    comment: '',
  },
  {
    moduleLabel: 'Relatório',
    moduleKey: 'relatorios',
    sectionLabel: '',
    label: 'Aposentados e Pensionistas',
    routePath: '/relatorios/aposentados-pensionistas/gestao',
    requiredRole: 'RELATORIO_APOSENTADO_PENSAO.GESTAO',
    featureFlag: '',
    backendModule: 'relatorios',
    comment: '',
  },
  {
    moduleLabel: 'Relatório',
    moduleKey: 'relatorios',
    sectionLabel: '',
    label: 'Repasse Fundo RH',
    routePath: '/relatorios/repasse-fundo/gestao',
    requiredRole: 'RELATORIO_REPASSE_FUNDO_RH.GESTAO',
    featureFlag: '',
    backendModule: 'relatorios',
    comment: '',
  },
  {
    moduleLabel: 'Relatório',
    moduleKey: 'relatorios',
    sectionLabel: '',
    label: 'Proventos e Descontos',
    routePath: '/relatorios/proventos-descontos/gestao',
    requiredRole: 'RELATORIO_PROVENTOS_DESCONTOS.GESTAO',
    featureFlag: '',
    backendModule: 'relatorios',
    comment: '',
  },
  {
    moduleLabel: 'Relatório',
    moduleKey: 'relatorios',
    sectionLabel: '',
    label: 'Relatório de Verbas',
    routePath: '/relatorios/verbas/gestao',
    requiredRole: 'RELATORIO_VERBAS.GESTAO',
    featureFlag: '',
    backendModule: 'relatorios',
    comment: '',
  },
  {
    moduleLabel: 'Relatório',
    moduleKey: 'relatorios',
    sectionLabel: '',
    label: 'Relatório de Estágio',
    routePath: '/relatorios/estagio/gestao',
    requiredRole: 'RELATORIO_ESTAGIO.GESTAO',
    featureFlag: '',
    backendModule: 'relatorios',
    comment: 'PDF/XLSX com limite de registros',
  },
  {
    moduleLabel: 'Relatório',
    moduleKey: 'relatorios',
    sectionLabel: '',
    label: 'Recrutamento e Seleção',
    routePath: '/relatorios/recrutamento/gestao',
    requiredRole: 'RELATORIO_GERENCIAL.GESTAO',
    featureFlag: '',
    backendModule: 'relatorios',
    comment: 'Relatório gerencial R&S',
  },
  {
    moduleLabel: 'Módulo Previdenciário',
    moduleKey: 'previdenciario',
    sectionLabel: 'Concessão',
    label: 'Regra de Aposentadoria',
    routePath: '/previdenciario/regra-aposentadoria/gestao',
    requiredRole: 'REGRA_APOSENTADORIA.GESTAO',
    featureFlag: '',
    backendModule: 'previdenciario',
    comment: 'Critérios legais por regime',
  },
  {
    moduleLabel: 'Módulo Previdenciário',
    moduleKey: 'previdenciario',
    sectionLabel: 'Concessão',
    label: 'Regra — nova',
    routePath: '/previdenciario/regra-aposentadoria/formulario',
    requiredRole: 'REGRA_APOSENTADORIA.CADASTRAR',
    featureFlag: '',
    backendModule: 'previdenciario',
    comment: '',
  },
  {
    moduleLabel: 'Módulo Previdenciário',
    moduleKey: 'previdenciario',
    sectionLabel: 'Concessão',
    label: 'Regra — editar',
    routePath: '/previdenciario/regra-aposentadoria/formulario/:id',
    requiredRole: 'REGRA_APOSENTADORIA.ATUALIZAR',
    featureFlag: '',
    backendModule: 'previdenciario',
    comment: '',
  },
  {
    moduleLabel: 'Módulo Previdenciário',
    moduleKey: 'previdenciario',
    sectionLabel: 'Concessão',
    label: 'Simulador de Aposentadoria',
    routePath: '/previdenciario/simulador-aposentadoria/gestao',
    requiredRole: 'REGRA_APOSENTADORIA.VISUALIZAR',
    featureFlag: '',
    backendModule: 'previdenciario',
    comment: 'Não persiste resultado como ato',
  },
  {
    moduleLabel: 'Módulo Previdenciário',
    moduleKey: 'previdenciario',
    sectionLabel: 'Concessão',
    label: 'Pensão',
    routePath: '/previdenciario/pensao/gestao',
    requiredRole: 'PENSAO.GESTAO',
    featureFlag: '',
    backendModule: 'previdenciario',
    comment: 'Beneficiários, rateio, reajuste',
  },
  {
    moduleLabel: 'Módulo Previdenciário',
    moduleKey: 'previdenciario',
    sectionLabel: 'Concessão',
    label: 'Compensação Previdenciária',
    routePath: '/previdenciario/compensacao/gestao',
    requiredRole: 'COMPENSACAO_PREVIDENCIARIA.GESTAO',
    featureFlag: '',
    backendModule: 'previdenciario',
    comment: 'Certidão + regime origem',
  },
  {
    moduleLabel: 'Módulo Previdenciário',
    moduleKey: 'previdenciario',
    sectionLabel: 'Concessão',
    label: 'Certidão de Tempo de Contribuição',
    routePath: '/previdenciario/certidao-tempo/gestao',
    requiredRole: 'CERTIDAO_TEMPO_CONTRIBUICAO.GESTAO',
    featureFlag: '',
    backendModule: 'previdenciario',
    comment: 'PDF gerado via S3',
  },
  {
    moduleLabel: 'Módulo Previdenciário',
    moduleKey: 'previdenciario',
    sectionLabel: 'Documentais',
    label: 'Declaração de Aposentado',
    routePath: '/previdenciario/declaracao-aposentado/gestao',
    requiredRole: 'RECADASTRAMENTO.GESTAO',
    featureFlag: '',
    backendModule: 'previdenciario',
    comment: 'PDF emitido por campanha ou avulso',
  },
  {
    moduleLabel: 'Módulo Previdenciário',
    moduleKey: 'previdenciario',
    sectionLabel: 'Documentais',
    label: 'Declaração de Ex-Servidor',
    routePath: '/previdenciario/declaracao-ex-servidor/gestao',
    requiredRole: 'RECADASTRAMENTO.GESTAO',
    featureFlag: '',
    backendModule: 'previdenciario',
    comment: '',
  },
  {
    moduleLabel: 'Módulo Previdenciário',
    moduleKey: 'previdenciario',
    sectionLabel: 'Documentais',
    label: 'Certidão de Compensação',
    routePath: '/previdenciario/certidao-compensacao/gestao',
    requiredRole: 'COMPENSACAO_PREVIDENCIARIA.GESTAO',
    featureFlag: '',
    backendModule: 'previdenciario',
    comment: '',
  },
  {
    moduleLabel: 'Módulo Previdenciário',
    moduleKey: 'previdenciario',
    sectionLabel: 'Operacionais',
    label: 'Prova de Vida / Recadastramento',
    routePath: '/previdenciario/recadastramento/gestao',
    requiredRole: 'RECADASTRAMENTO.GESTAO',
    featureFlag: 'PROVA_VIDA_PUBLIC_API_ENABLED',
    backendModule: 'previdenciario',
    comment: 'Carteira; campanha; histórico ligação',
  },
  {
    moduleLabel: 'Módulo Previdenciário',
    moduleKey: 'previdenciario',
    sectionLabel: 'Operacionais',
    label: 'Recadastramento — atendimento',
    routePath: '/previdenciario/recadastramento/formulario/:id',
    requiredRole: 'RECADASTRAMENTO.GESTAO',
    featureFlag: '',
    backendModule: 'previdenciario',
    comment: 'Emite comprovante se RECADASTRADO',
  },
  {
    moduleLabel: 'Módulo Previdenciário',
    moduleKey: 'previdenciario',
    sectionLabel: 'Operacionais',
    label: 'Transferência Previdenciária',
    routePath: '/previdenciario/transferencia-previdenciaria/gestao',
    requiredRole: 'ARQUIVO_EXPORTACAO_SIPREV.GESTAO',
    featureFlag: '',
    backendModule: 'previdenciario',
    comment: 'Exportação SIPREV XML',
  },
  {
    moduleLabel: 'Módulo Previdenciário',
    moduleKey: 'previdenciario',
    sectionLabel: 'Operacionais',
    label: 'Relatórios Previdenciários',
    routePath: '/previdenciario/relatorios/gestao',
    requiredRole: 'RELATORIO_APOSENTADO_PENSAO.GESTAO',
    featureFlag: '',
    backendModule: 'previdenciario',
    comment: 'Carteira, concessões, pensões',
  },
  {
    moduleLabel: 'Auditoria',
    moduleKey: 'auditoria',
    sectionLabel: '',
    label: 'Consulta de Trilha',
    routePath: '/auditoria/trilha/gestao',
    requiredRole: 'AUDITORIA.GESTAO',
    featureFlag: 'AUDIT_FULL_TRACE_ENABLED',
    backendModule: 'auditoria',
    comment: 'Tabela audit_log; filtros combinados',
  },
  {
    moduleLabel: 'Auditoria',
    moduleKey: 'auditoria',
    sectionLabel: '',
    label: 'Detalhe de Evento',
    routePath: '/auditoria/trilha/detalhes/:id',
    requiredRole: 'AUDITORIA.GESTAO',
    featureFlag: '',
    backendModule: 'auditoria',
    comment: 'Diff JSONB renderizado',
  },
  {
    moduleLabel: 'Auditoria',
    moduleKey: 'auditoria',
    sectionLabel: '',
    label: 'Relatório de Auditoria',
    routePath: '/auditoria/relatorio/gestao',
    requiredRole: 'AUDITORIA.GESTAO',
    featureFlag: '',
    backendModule: 'auditoria',
    comment: 'PDF/XLSX por período',
  },
  {
    moduleLabel: 'Auditoria',
    moduleKey: 'auditoria',
    sectionLabel: '',
    label: 'Filtros por Entidade',
    routePath: '/auditoria/entidade/gestao',
    requiredRole: 'AUDITORIA.GESTAO',
    featureFlag: '',
    backendModule: 'auditoria',
    comment: 'Pesquisa por domínio e entidade_id',
  },
  {
    moduleLabel: 'Auditoria',
    moduleKey: 'auditoria',
    sectionLabel: '',
    label: 'Filtros por Usuário',
    routePath: '/auditoria/usuario/gestao',
    requiredRole: 'AUDITORIA.GESTAO',
    featureFlag: '',
    backendModule: 'auditoria',
    comment: '',
  },
  {
    moduleLabel: 'Auditoria',
    moduleKey: 'auditoria',
    sectionLabel: '',
    label: 'Filtros por Período',
    routePath: '/auditoria/periodo/gestao',
    requiredRole: 'AUDITORIA.GESTAO',
    featureFlag: '',
    backendModule: 'auditoria',
    comment: 'Particionamento por ano/mês',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'Agenda',
    label: 'Configurar Agenda Médica',
    routePath: '/saude/agenda-medica/formulario',
    requiredRole: 'AGENDA_MEDICA.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: 'Médico × especialidade × janelas',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'Agenda',
    label: 'Configurar — editar',
    routePath: '/saude/agenda-medica/formulario/:id',
    requiredRole: 'AGENDA_MEDICA.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: '',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'Agenda',
    label: 'Painel de Agenda',
    routePath: '/saude/agenda-medica/gestao',
    requiredRole: 'AGENDA_MEDICA.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: 'Calendário semanal/mensal; status janelas',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'Perícia',
    label: 'Atendimento Agendado',
    routePath: '/saude/pericia/agendados/gestao',
    requiredRole: 'PERICIA_MEDICA.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: 'Servidor deve estar ATIVO/EM_EXERCICIO',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'Perícia',
    label: 'Atendimento Pendente',
    routePath: '/saude/pericia/pendentes/gestao',
    requiredRole: 'PERICIA_MEDICA.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: 'Status PENDENTE ou NAO_COMPARECEU',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'Perícia',
    label: 'Prontuário',
    routePath: '/saude/pericia/prontuario/formulario/:id',
    requiredRole: 'PERICIA_MEDICA.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: 'CID, ação pericial, tipo laudo',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'Perícia',
    label: 'Validação de Laudo',
    routePath: '/saude/pericia/validacao-laudo/gestao',
    requiredRole: 'PERICIA_MEDICA.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: 'PENDENTE_VALIDACAO → APROVADO/REPROVADO',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'Perícia',
    label: 'Licença Médica',
    routePath: '/saude/licenca-medica/gestao',
    requiredRole: 'LICENCA_MEDICA.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: 'Máx. 720 dias acumulados',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'Perícia',
    label: 'Licença — formulário',
    routePath: '/saude/licenca-medica/formulario/:id',
    requiredRole: 'LICENCA_MEDICA.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: 'Equipe, CID, restrições, readaptação',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'Suporte Clínico',
    label: 'Médico',
    routePath: '/saude/medico/gestao',
    requiredRole: 'MEDICO.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: 'CRM, UF, especialidades, vínculos',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'Suporte Clínico',
    label: 'Especialidade Médica',
    routePath: '/saude/especialidade-medica/gestao',
    requiredRole: 'ESPECIALIDADE_MEDICA.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: '',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'Suporte Clínico',
    label: 'Exame Ocupacional',
    routePath: '/saude/exame/gestao',
    requiredRole: 'EXAME.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: '',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'Suporte Clínico',
    label: 'Entidade de Exames',
    routePath: '/saude/entidade-exame/gestao',
    requiredRole: 'ENTIDADE_EXAME.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: 'Laboratórios / clínicas credenciadas',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'Suporte Clínico',
    label: 'Profissional de Saúde',
    routePath: '/saude/profissional-saude/gestao',
    requiredRole: 'PROFISSIONAL_SAUDE.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: 'Outros profissionais da equipe pericial',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'SST',
    label: 'Acidente de Trabalho',
    routePath: '/saude/acidente-trabalho/gestao',
    requiredRole: 'ACIDENTE_TRABALHO.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: 'CAT; CID; dias afastamento',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'SST',
    label: 'CID',
    routePath: '/saude/cid/gestao',
    requiredRole: 'CID.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: 'Tabela CID-10',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'SST',
    label: 'Categoria de Doenças',
    routePath: '/saude/categoria-doenca/gestao',
    requiredRole: 'CATEGORIA_DOENCA.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: '',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'SST',
    label: 'Subcategoria de Doenças',
    routePath: '/saude/subcategoria-doenca/gestao',
    requiredRole: 'SUBCATEGORIA_DOENCA.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: '',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'SST',
    label: 'Agente Nocivo',
    routePath: '/saude/agente-nocivo/gestao',
    requiredRole: 'AGENTE_NOCIVO.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: 'Classificação legal',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'SST',
    label: 'EPI',
    routePath: '/saude/epi/gestao',
    requiredRole: 'EPI.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: 'Equipamento de Proteção Individual',
  },
  {
    moduleLabel: 'Ponto Eletrônico',
    moduleKey: 'ponto',
    sectionLabel: 'Jornadas',
    label: 'Jornadas e Atribuições',
    routePath: '/ponto/jornadas',
    requiredRole: 'PONTO.JORNADAS',
    featureFlag: '',
    backendModule: 'ponto',
    comment: 'Portaria MTP 671/2021: jornada contratada, turnos e vigências',
  },
  {
    moduleLabel: 'Ponto Eletrônico',
    moduleKey: 'ponto',
    sectionLabel: 'REP',
    label: 'Equipamentos e Ingestão',
    routePath: '/ponto/rep',
    requiredRole: 'PONTO.REP',
    featureFlag: '',
    backendModule: 'ponto',
    comment: 'REP-P, REP-A e REP-C: cadastro, AFDT e lotes',
  },
  {
    moduleLabel: 'Ponto Eletrônico',
    moduleKey: 'ponto',
    sectionLabel: 'AFD',
    label: 'Geração e Importação',
    routePath: '/ponto/afd',
    requiredRole: 'PONTO.AFD',
    featureFlag: '',
    backendModule: 'ponto',
    comment: 'Arquivo Fonte de Dados: geração, importação, selo e histórico',
  },
  {
    moduleLabel: 'Ponto Eletrônico',
    moduleKey: 'ponto',
    sectionLabel: 'Escalas',
    label: 'Escalas e Plantões',
    routePath: '/ponto/escalas',
    requiredRole: 'PONTO.ESCALAS',
    featureFlag: '',
    backendModule: 'ponto',
    comment: 'Ciclos 12x36, 6x1, plantões, rosters e flags noturnas/insalubres',
  },
  {
    moduleLabel: 'Ponto Eletrônico',
    moduleKey: 'ponto',
    sectionLabel: 'Banco de Horas',
    label: 'Banco de Horas',
    routePath: '/ponto/banco-horas',
    requiredRole: 'PONTO.BANCO_HORAS',
    featureFlag: '',
    backendModule: 'ponto',
    comment: 'Saldo, prazo, extrato e ajuste auditado',
  },
  {
    moduleLabel: 'Área de Saúde / Junta Médica',
    moduleKey: 'saude',
    sectionLabel: 'SST',
    label: 'EPC',
    routePath: '/saude/epc/gestao',
    requiredRole: 'EPC.GESTAO',
    featureFlag: '',
    backendModule: 'saude',
    comment: 'Equipamento de Proteção Coletiva',
  },
  {
    moduleLabel: 'Convênio',
    moduleKey: 'convenio',
    sectionLabel: '',
    label: 'Convênios',
    routePath: '/convenio/convenio/gestao',
    requiredRole: 'CONVENIO.GESTAO',
    featureFlag: '',
    backendModule: 'convenio',
    comment: 'Vigência, banco de cobrança',
  },
  {
    moduleLabel: 'Convênio',
    moduleKey: 'convenio',
    sectionLabel: '',
    label: 'Convênio — novo',
    routePath: '/convenio/convenio/formulario',
    requiredRole: 'CONVENIO.CADASTRAR',
    featureFlag: '',
    backendModule: 'convenio',
    comment: '',
  },
  {
    moduleLabel: 'Convênio',
    moduleKey: 'convenio',
    sectionLabel: '',
    label: 'Convênio — editar',
    routePath: '/convenio/convenio/formulario/:id',
    requiredRole: 'CONVENIO.ATUALIZAR',
    featureFlag: '',
    backendModule: 'convenio',
    comment: '',
  },
  {
    moduleLabel: 'Convênio',
    moduleKey: 'convenio',
    sectionLabel: '',
    label: 'Beneficiários',
    routePath: '/convenio/beneficiario/gestao',
    requiredRole: 'CONVENIO_BENEFICIARIO.GESTAO',
    featureFlag: '',
    backendModule: 'convenio',
    comment: 'Valor mensal, início, fim',
  },
  {
    moduleLabel: 'Convênio',
    moduleKey: 'convenio',
    sectionLabel: '',
    label: 'Descontos em Folha',
    routePath: '/convenio/desconto-folha/gestao',
    requiredRole: 'CONVENIO_DESCONTO_FOLHA.GESTAO',
    featureFlag: '',
    backendModule: 'convenio',
    comment: 'Por competência; lançado na folha',
  },
  {
    moduleLabel: 'Fiscal',
    moduleKey: 'fiscal',
    sectionLabel: 'Obrigações',
    label: 'DCTFWeb',
    routePath: '/fiscal/dctfweb',
    requiredRole: 'DCTFWEB.GESTAO',
    featureFlag: '',
    backendModule: 'fiscal',
    comment: 'Geração, assinatura e transmissão da DCTFWeb',
  },
  {
    moduleLabel: 'Fiscal',
    moduleKey: 'fiscal',
    sectionLabel: 'Obrigações',
    label: 'GPS residual',
    routePath: '/fiscal/gps-residual',
    requiredRole: 'GPS.GESTAO',
    featureFlag: '',
    backendModule: 'fiscal',
    comment: 'Safety-net de recolhimentos RGPS fora da DCTFWeb',
  },
] as const satisfies readonly FeatureEntry[];

export const ADMIN_MODULES: ReadonlyArray<{
  key: AdminModuleKey;
  label: string;
  routePath: string;
}> = [
  { key: 'gestao', label: 'Gestão', routePath: '/gestao' },
  { key: 'rh', label: 'Módulo RH', routePath: '/rh' },
  { key: 'folha', label: 'Folha de Pgt', routePath: '/folha' },
  { key: 'avaliacao', label: 'Módulo Avaliação', routePath: '/avaliacao' },
  { key: 'recrutamento', label: 'Recrutamento e Seleção', routePath: '/recrutamento' },
  { key: 'consultas', label: 'Consultas Gerenciais', routePath: '/consultas' },
  { key: 'relatorios', label: 'Relatório', routePath: '/relatorios' },
  { key: 'previdenciario', label: 'Módulo Previdenciário', routePath: '/previdenciario' },
  { key: 'auditoria', label: 'Auditoria', routePath: '/auditoria' },
  { key: 'saude', label: 'Área de Saúde', routePath: '/saude' },
  { key: 'ponto', label: 'Ponto Eletrônico', routePath: '/ponto' },
  { key: 'convenio', label: 'Convênio', routePath: '/convenio' },
  { key: 'fiscal', label: 'Fiscal', routePath: '/fiscal' },
];

export const ADMIN_FEATURES: AdminFeature[] = ADMIN_FEATURE_CATALOG.map((entry, index) => ({
  id: `admin-feature-${String(index + 1).padStart(3, '0')}`,
  ...entry,
  childPath: childPathFromRoute(entry.routePath),
  requiredPermissions: permissionsForRoutePath(entry.routePath),
  mode: featureModeFromRoute(entry.routePath),
}));

export const ADMIN_NAVIGATION_SECTIONS: AdminNavigationSection[] = ADMIN_MODULES.map((module) => ({
  moduleLabel: module.label,
  moduleKey: module.key,
  routePath: module.routePath,
  items: ADMIN_FEATURES.filter((feature) => feature.moduleKey === module.key),
}));

export const ADMIN_FEATURES_BY_MODULE: Record<AdminModuleKey, AdminFeature[]> =
  ADMIN_MODULES.reduce(
    (accumulator, module) => ({
      ...accumulator,
      [module.key]: ADMIN_FEATURES.filter((feature) => feature.moduleKey === module.key),
    }),
    {} as Record<AdminModuleKey, AdminFeature[]>,
  );

export function findAdminFeatureByRoutePath(routePath: string): AdminFeature | undefined {
  const normalizedPath = routePath.split('?')[0].split('#')[0].replace(/\/$/, '');
  return ADMIN_FEATURES.find((feature) => feature.routePath === normalizedPath);
}

function childPathFromRoute(routePath: string): string {
  const [, ...parts] = routePath.split('/').filter(Boolean);
  return parts.join('/');
}

function featureModeFromRoute(routePath: string): AdminFeatureMode {
  if (routePath.includes('/formulario')) return 'form';
  if (routePath.includes('/detalhes')) return 'details';
  if (routePath.endsWith('/dashboard')) return 'dashboard';
  return 'management';
}
