// Generated by backend/scripts/gen-permissions.ts. Do not edit by hand.
export const ROUTE_PERMISSION_MAP = [
  ['#!/auditoria/**', 'auditoria.read'],
  ['#!/avaliacao/**', 'avaliacao.read'],
  ['#!/avaliacao/**', 'avaliacao.write'],
  ['#!/consultas/**', 'consultas.read'],
  ['#!/contracheques/**', 'portal.paystub.read'],
  ['#!/convenios/**', 'convenio.read'],
  ['#!/convenios/**', 'convenio.write'],
  ['#!/documentos/**', 'documents.upload'],
  ['#!/documentos/**', 'documents.register'],
  ['#!/documentos/**', 'documents.download'],
  ['#!/esocial/**', 'esocial.event.read'],
  ['#!/esocial/**', 'esocial.event.write'],
  ['#!/esocial/**', 'esocial.event.exclude'],
  ['#!/esocial/**', 'esocial.submission.read'],
  ['#!/esocial/**', 'esocial.submission.retry'],
  ['#!/folha/contracheques/**', 'report.payslip.read'],
  ['#!/folha/contracheques/**', 'report.payslip.write'],
  ['#!/folha/fgts/**', 'payroll.fgts.read'],
  ['#!/folha/fgts/**', 'payroll.fgts.write'],
  ['#!/folha/pis-pasep/**', 'payroll.payroll.read'],
  ['#!/folha/pis-pasep/**', 'payroll.payroll.write'],
  ['#!/folha/remessa-bancaria/**', 'payment.remittance.read'],
  ['#!/folha/remessa-bancaria/**', 'payment.remittance.write'],
  ['#!/folha/simulacao', 'payroll.simulation.execute'],
  ['#!/folhaPagamento/**', 'folha.read'],
  ['#!/folhaPagamento/**', 'folha.write'],
  ['#!/funcionario/**', 'rh.employee.read'],
  ['#!/gestao/**', 'gestao.read'],
  ['#!/gestao/**', 'gestao.write'],
  ['#!/gestao/parametros/ats', 'payroll.ats.read'],
  ['#!/gestao/parametros/ats', 'payroll.ats.write'],
  ['#!/gestao/parametros/irrf', 'system.tax-rate.read'],
  ['#!/gestao/parametros/irrf', 'system.tax-rate.write'],
  ['#!/gestao/parametros/teto-remuneratorio', 'system.parameter.read'],
  ['#!/gestao/parametros/teto-remuneratorio', 'system.parameter.write'],
  ['#!/ponto/jornadas/**', 'ponto.schedule.read'],
  ['#!/ponto/jornadas/**', 'ponto.schedule.write'],
  ['#!/previdenciario/**', 'previdenciario.read'],
  ['#!/previdenciario/**', 'previdenciario.write'],
  ['#!/recrutamento/**', 'recrutamento.read'],
  ['#!/recrutamento/**', 'recrutamento.write'],
  ['#!/relatorio/**', 'relatorio.read'],
  ['#!/relatorio/**', 'relatorio.generate'],
  ['#!/saude/**', 'saude.read'],
  ['#!/saude/**', 'saude.write'],
  ['#!/saude/acidentes/**', 'saude.cat.read'],
  ['#!/saude/acidentes/**', 'saude.cat.write'],
  ['#!/saude/epi/**', 'saude.epi.read'],
  ['#!/saude/epi/**', 'saude.epi.write'],
  ['#!/saude/exposicoes/**', 'saude.exposure.read'],
  ['#!/saude/exposicoes/**', 'saude.exposure.write'],
  ['#!/saude/programas/**', 'saude.program.read'],
  ['#!/saude/programas/**', 'saude.program.write'],
] as const;

export function permissionsForRoutePath(routePath: string): string[] {
  return ROUTE_PERMISSION_MAP.filter(([pattern]) => routeMatches(pattern, routePath)).map(
    ([, permission]) => permission,
  );
}

function routeMatches(pattern: string, routePath: string): boolean {
  const normalizedPattern = pattern.replace(/^#!/, '').replace(/\/\*\*$/, '');
  const normalizedRoute = routePath.replace(/^#!/, '');
  return normalizedRoute.startsWith(normalizedPattern);
}
