// Generated by backend/scripts/gen-permissions.ts. Do not edit by hand.
export const ROUTE_PERMISSION_MAP = [
  ['#!/auditoria/**', 'auditoria.read'],
  ['#!/avaliacao/**', 'avaliacao.read'],
  ['#!/avaliacao/**', 'avaliacao.write'],
  ['#!/consultas/**', 'consultas.read'],
  ['#!/convenios/**', 'convenio.read'],
  ['#!/convenios/**', 'convenio.write'],
  ['#!/documentos/**', 'documents.upload'],
  ['#!/documentos/**', 'documents.register'],
  ['#!/documentos/**', 'documents.download'],
  ['#!/folhaPagamento/**', 'folha.read'],
  ['#!/folhaPagamento/**', 'folha.write'],
  ['#!/funcionario/**', 'rh.read'],
  ['#!/funcionario/**', 'rh.write'],
  ['#!/gestao/**', 'gestao.read'],
  ['#!/gestao/**', 'gestao.write'],
  ['#!/previdenciario/**', 'previdenciario.read'],
  ['#!/previdenciario/**', 'previdenciario.write'],
  ['#!/recrutamento/**', 'recrutamento.read'],
  ['#!/recrutamento/**', 'recrutamento.write'],
  ['#!/relatorio/**', 'relatorio.read'],
  ['#!/relatorio/**', 'relatorio.generate'],
  ['#!/saude/**', 'saude.read'],
  ['#!/saude/**', 'saude.write'],
] as const;

export function permissionsForRoutePath(routePath: string): string[] {
  return ROUTE_PERMISSION_MAP.filter(([pattern]) => routeMatches(pattern, routePath)).map(
    ([, permission]) => permission,
  );
}

function routeMatches(pattern: string, routePath: string): boolean {
  const normalizedPattern = pattern.replace(/^#!/, '').replace(/\/\*\*$/, '');
  const normalizedRoute = routePath.replace(/^#!/, '');
  return normalizedRoute.startsWith(normalizedPattern);
}
