-- Generated by scripts/check-db.mjs fk-coverage write.
-- Non-destructive orphan report for inferred foreign keys.

WITH orphan_counts AS (
  SELECT 'hr.merit_progression.administrative_process_id' AS check_name, count(*)::bigint AS orphan_count
  FROM hr.merit_progression child
  LEFT JOIN hr.administrative_process parent ON parent.id = child.administrative_process_id
  WHERE child.administrative_process_id IS NOT NULL AND parent.id IS NULL
)
SELECT * FROM orphan_counts WHERE orphan_count > 0 ORDER BY check_name;

DO $$
DECLARE
  orphan_total bigint;
BEGIN
  WITH orphan_counts AS (
    SELECT count(*)::bigint AS orphan_count
    FROM hr.merit_progression child
    LEFT JOIN hr.administrative_process parent ON parent.id = child.administrative_process_id
    WHERE child.administrative_process_id IS NOT NULL AND parent.id IS NULL
  )
  SELECT coalesce(sum(orphan_count), 0) INTO orphan_total FROM orphan_counts;

  IF orphan_total > 0 THEN
    RAISE EXCEPTION 'Inferred FK orphan rows detected: %', orphan_total;
  END IF;
END
$$;
