-- ============================================================
-- Worker A Core DDL: tables chunk 2
-- Schema: dbo
-- Tables: 50
-- Range: empresa_filial .. municipio
-- Includes columns, defaults, NOT NULL, identity, primary keys, and unique constraints.
-- ============================================================

CREATE TABLE dbo.empresa_filial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sigla TEXT,
    nome_filial TEXT NOT NULL,
    empresa_matriz BOOLEAN,
    tipo_filial TEXT NOT NULL,
    cnae_id BIGINT NOT NULL,
    codigo_pagamento_gps_id BIGINT NOT NULL,
    situacao TEXT NOT NULL,
    esfera_orgao TEXT NOT NULL,
    qtd_proprietario INTEGER,
    tipo_estabelecimento TEXT NOT NULL,
    capital_social_anual DOUBLE PRECISION NOT NULL,
    dt_inicial_atividade TIMESTAMP WITH TIME ZONE,
    referencia_contribuicao TEXT NOT NULL,
    atividade_primaria TEXT NOT NULL,
    natureza_estabelecimento TEXT NOT NULL,
    banco_id BIGINT NOT NULL,
    agencia INTEGER NOT NULL,
    fpas INTEGER NOT NULL,
    cd_gpras_acidente_trabalho INTEGER,
    cnpj TEXT,
    codigo_empregador INTEGER,
    rais_negativa INTEGER NOT NULL,
    percentual_empregador DOUBLE PRECISION,
    sat DOUBLE PRECISION,
    salario_educacao DOUBLE PRECISION,
    senai DOUBLE PRECISION,
    sesi DOUBLE PRECISION,
    senac DOUBLE PRECISION,
    sesc DOUBLE PRECISION,
    sebrae DOUBLE PRECISION,
    senar DOUBLE PRECISION,
    senat DOUBLE PRECISION,
    set_col DOUBLE PRECISION,
    secoop DOUBLE PRECISION,
    dpc DOUBLE PRECISION,
    forca_aerea DOUBLE PRECISION,
    fap INTEGER,
    logradouro TEXT,
    numero TEXT,
    complemento TEXT,
    cep TEXT,
    uf_id BIGINT,
    bairro TEXT,
    municipio_id BIGINT,
    telefone TEXT,
    anexo_id BIGINT,
    tipo_inscricao TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    pais_id BIGINT,
    cei TEXT,
    CONSTRAINT pk_empresa_filial PRIMARY KEY (id)
);

CREATE TABLE dbo.empresa_filial_lotacao (
    empresa_filial_id BIGINT NOT NULL,
    lotacao_id BIGINT NOT NULL,
    CONSTRAINT pk_empresa_filial_lotacao PRIMARY KEY (empresa_filial_id, lotacao_id)
);

CREATE TABLE dbo.entidade_exame (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    bairro TEXT,
    cep TEXT,
    complemento TEXT,
    logradouro TEXT,
    numero TEXT,
    telefone TEXT,
    tipo TEXT NOT NULL,
    municipio_id BIGINT,
    tomador_servico_id BIGINT NOT NULL,
    uf_id BIGINT,
    CONSTRAINT pk_entidade_exame PRIMARY KEY (id)
);

CREATE TABLE dbo.entidade_exame_exame (
    entidade_exame_id BIGINT NOT NULL,
    exame_id BIGINT NOT NULL,
    CONSTRAINT pk_entidade_exame_exame PRIMARY KEY (entidade_exame_id, exame_id)
);

CREATE TABLE dbo.equipamento_protecao_coletiva (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    tipo_protecao TEXT NOT NULL,
    descricao TEXT NOT NULL,
    validade TIMESTAMP WITH TIME ZONE NOT NULL,
    certificado TEXT NOT NULL,
    referencia TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    minimo INTEGER,
    livre INTEGER,
    atual INTEGER,
    CONSTRAINT pk_equipamento_protecao_coletiva PRIMARY KEY (id)
);

CREATE TABLE dbo.equipamento_protecao_individual (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    tipo_protecao TEXT NOT NULL,
    descricao TEXT NOT NULL,
    validade TIMESTAMP WITH TIME ZONE NOT NULL,
    certificado TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    minimo INTEGER,
    livre INTEGER,
    atual INTEGER,
    CONSTRAINT pk_equipamento_protecao_individual PRIMARY KEY (id)
);

CREATE TABLE dbo.esocial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    descricao TEXT NOT NULL,
    CONSTRAINT pk_esocial PRIMARY KEY (id)
);

CREATE TABLE dbo.etapa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo INTEGER NOT NULL,
    descricao TEXT NOT NULL,
    processo TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_etapa PRIMARY KEY (id)
);

CREATE TABLE dbo.evento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao TEXT NOT NULL,
    situacao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_evento PRIMARY KEY (id)
);

CREATE TABLE dbo.exame (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    categoria TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_exame PRIMARY KEY (id)
);

CREATE TABLE dbo.experiencia_profissional (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    funcao_id BIGINT NOT NULL,
    CONSTRAINT pk_experiencia_profissional PRIMARY KEY (id)
);

CREATE TABLE dbo.faixa_salarial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_grupo_salarial BIGINT NOT NULL,
    id_classe_salarial BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_faixa_salarial PRIMARY KEY (id)
);

CREATE TABLE dbo.faixa_salarial_nivel (
    id_faixa_salarial BIGINT NOT NULL,
    id_nivel_salarial BIGINT NOT NULL
);

CREATE TABLE dbo.falta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT NOT NULL,
    data DATE,
    data_inicio TIMESTAMP WITH TIME ZONE NOT NULL,
    data_retorno TIMESTAMP WITH TIME ZONE,
    motivo_afastamento_id BIGINT NOT NULL,
    afastamento_id BIGINT NOT NULL,
    diagnostico_medico TEXT NOT NULL,
    observacao_documento TEXT,
    anexo_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_falta PRIMARY KEY (id)
);

CREATE TABLE dbo.ferias_programacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT NOT NULL,
    exercicio_inicio DATE NOT NULL,
    exercicio_fim DATE NOT NULL,
    data_limite DATE NOT NULL,
    quant_faltas TEXT,
    tipo_ferias TEXT NOT NULL,
    quant_dias TEXT NOT NULL,
    abono_peculiario BOOLEAN,
    decimo_terceiro BOOLEAN,
    situacao TEXT NOT NULL,
    mes_competencia_particao_um TEXT,
    dias_a_gozar_um TEXT,
    tipo_processamento_um TEXT,
    data_inicial_um DATE,
    data_final_um DATE,
    situacao_um TEXT,
    mes_competencia_particao_dois TEXT,
    dias_a_gozar_dois TEXT,
    tipo_processamento_dois TEXT,
    data_inicial_dois DATE,
    data_final_dois DATE,
    situacao_dois TEXT,
    mes_competencia_particao_tres TEXT,
    dias_a_gozar_tres TEXT,
    tipo_processamento_tres TEXT,
    data_inicial_tres DATE,
    data_final_tres DATE,
    situacao_tres TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    motivo TEXT,
    CONSTRAINT pk_ferias_programacao PRIMARY KEY (id)
);

CREATE TABLE dbo.flyway_schema_history (
    installed_rank INTEGER NOT NULL,
    version TEXT,
    description TEXT,
    type TEXT NOT NULL,
    script TEXT NOT NULL,
    checksum INTEGER,
    installed_by TEXT NOT NULL,
    installed_on TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    execution_time INTEGER NOT NULL,
    success BOOLEAN NOT NULL,
    CONSTRAINT pk_flyway_schema_history PRIMARY KEY (installed_rank)
);

CREATE TABLE dbo.folha_competencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    inicio_competencia TIMESTAMP WITH TIME ZONE NOT NULL,
    fim_competencia TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    mes_competencia INTEGER,
    ano_competencia INTEGER,
    CONSTRAINT pk_folha_competencia PRIMARY KEY (id)
);

CREATE TABLE dbo.folha_pagamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_processamento_id BIGINT NOT NULL,
    periodo_processamento_inicio TIMESTAMP WITH TIME ZONE NOT NULL,
    periodo_processamento_fim TIMESTAMP WITH TIME ZONE,
    status TEXT NOT NULL,
    empresa_filial_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    folha_competencia_id BIGINT,
    CONSTRAINT pk_folha_pagamento PRIMARY KEY (id)
);

CREATE TABLE dbo.folha_pagamento_funcionario_verba (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT NOT NULL,
    folha_pagamento_id BIGINT NOT NULL,
    verba_id BIGINT,
    valor_referencia DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    situacao TEXT,
    valor DOUBLE PRECISION DEFAULT 0,
    adicionado_manualmente BOOLEAN,
    CONSTRAINT pk_folha_pagamento_funcionario_verba PRIMARY KEY (id)
);

CREATE TABLE dbo.folha_pagamento_lotacao (
    folha_pagamento_id BIGINT NOT NULL,
    lotacao_id BIGINT NOT NULL,
    CONSTRAINT pk_folha_pagamento_lotacao PRIMARY KEY (folha_pagamento_id, lotacao_id)
);

CREATE TABLE dbo.frequencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT NOT NULL,
    data DATE,
    horas_trabalhadas TIMESTAMP WITH TIME ZONE,
    hora_extra TIMESTAMP WITH TIME ZONE,
    entrada_um TIMESTAMP WITH TIME ZONE,
    saida_um TIMESTAMP WITH TIME ZONE,
    entrada_dois TIMESTAMP WITH TIME ZONE,
    saida_dois TIMESTAMP WITH TIME ZONE,
    falta_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_frequencia PRIMARY KEY (id)
);

CREATE TABLE dbo.funcao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome TEXT NOT NULL,
    descricao TEXT,
    cbo_id BIGINT NOT NULL,
    data_criacao TIMESTAMP WITH TIME ZONE NOT NULL,
    data_extincao TIMESTAMP WITH TIME ZONE,
    funcao_extinta BOOLEAN,
    natureza_funcao_id BIGINT,
    processo_funcao_id BIGINT,
    categoria_profissional_id BIGINT,
    dedicacao_exclusiva BOOLEAN,
    funcao_acumulavel TEXT,
    contagem_tempo_especial TEXT,
    motivo_lei TEXT,
    numero_lei INTEGER,
    data_lei TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    grupo_salarial_id BIGINT,
    centro_custo_id BIGINT,
    CONSTRAINT pk_funcao PRIMARY KEY (id)
);

CREATE TABLE dbo.funcao_atividade (
    funcao_id BIGINT NOT NULL,
    atividade_id BIGINT NOT NULL,
    CONSTRAINT pk_funcao_atividade PRIMARY KEY (funcao_id, atividade_id)
);

CREATE TABLE dbo.funcao_curso (
    funcao_id BIGINT NOT NULL,
    curso_id BIGINT NOT NULL,
    CONSTRAINT pk_funcao_curso PRIMARY KEY (funcao_id, curso_id)
);

CREATE TABLE dbo.funcao_habilidade (
    funcao_id BIGINT NOT NULL,
    habilidade_id BIGINT NOT NULL,
    CONSTRAINT pk_funcao_habilidade PRIMARY KEY (funcao_id, habilidade_id)
);

CREATE TABLE dbo.funcao_historico_lei (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    motivo_lei TEXT NOT NULL,
    numero_lei INTEGER NOT NULL,
    data_lei TIMESTAMP WITH TIME ZONE NOT NULL,
    funcao_id BIGINT NOT NULL,
    CONSTRAINT pk_funcao_historico_lei PRIMARY KEY (id)
);

CREATE TABLE dbo.funcao_requisito (
    funcao_id BIGINT NOT NULL,
    requisito_id BIGINT NOT NULL,
    CONSTRAINT pk_funcao_requisito PRIMARY KEY (funcao_id, requisito_id)
);

CREATE TABLE dbo.funcao_verba (
    funcao_id BIGINT NOT NULL,
    verba_id BIGINT NOT NULL,
    CONSTRAINT pk_funcao_verba PRIMARY KEY (funcao_id, verba_id)
);

CREATE TABLE dbo.funcao_vinculo (
    funcao_id BIGINT NOT NULL,
    vinculo_id BIGINT NOT NULL,
    CONSTRAINT pk_funcao_vinculo PRIMARY KEY (funcao_id, vinculo_id)
);

CREATE TABLE dbo.funcionario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    nome TEXT NOT NULL,
    matricula INTEGER NOT NULL,
    empresa_id BIGINT NOT NULL,
    filial_id BIGINT NOT NULL,
    sexo TEXT,
    estado_civil TEXT,
    grau_instrucao TEXT,
    dt_nascimento TIMESTAMP WITH TIME ZONE NOT NULL,
    nacionalidade_id BIGINT,
    municipio_id BIGINT,
    naturalidade TEXT,
    conhecido_como TEXT,
    tipo_sanguineo TEXT,
    cor_pele TEXT,
    nome_mae TEXT NOT NULL,
    nome_pai TEXT,
    registro_estrangeiro_uf_id BIGINT,
    municipio_registro_id BIGINT,
    uf_id BIGINT NOT NULL,
    estrangeiro BOOLEAN,
    naturalizado BOOLEAN,
    casamento_brasileiro BOOLEAN,
    filho_brasileiro BOOLEAN,
    logradouro TEXT NOT NULL,
    numero TEXT NOT NULL,
    complemento TEXT,
    bairro TEXT NOT NULL,
    cep TEXT NOT NULL,
    email_pessoal TEXT,
    email_corporativo TEXT,
    telefone_principal TEXT,
    telefone_opcional TEXT,
    orgao_expeditor_uf_id BIGINT NOT NULL,
    ctps_uf_id BIGINT,
    identidade TEXT NOT NULL,
    orgao_expeditor TEXT NOT NULL,
    dt_expedicao_rg TIMESTAMP WITH TIME ZONE NOT NULL,
    numero_ctps TEXT,
    cpf TEXT NOT NULL,
    pis_pasep TEXT NOT NULL,
    dt_emissao_pis_pasep TIMESTAMP WITH TIME ZONE,
    agencia_pis_pasep INTEGER,
    titulo_eleitor INTEGER,
    cnh INTEGER,
    dt_validade_cnh TIMESTAMP WITH TIME ZONE,
    categoria_cnh TEXT,
    registro_alistamento INTEGER,
    numero_processo INTEGER,
    numero_ato INTEGER,
    dt_nomeacao TIMESTAMP WITH TIME ZONE,
    numero_diario_oficial INTEGER,
    dt_publicacao_diario_oficial TIMESTAMP WITH TIME ZONE,
    titulo_eleitor_uf_id BIGINT,
    vinculo_id BIGINT NOT NULL,
    funcao_id BIGINT NOT NULL,
    municipio_trabalho_id BIGINT,
    lotacao_id BIGINT,
    banco_id BIGINT NOT NULL,
    jornada_trabalho_turno_id BIGINT NOT NULL,
    sindicato_id BIGINT,
    tp_sit_func_afastamento_id BIGINT,
    motivo_afastamento_id BIGINT,
    dt_admissao TIMESTAMP WITH TIME ZONE NOT NULL,
    n_dependentes_ir INTEGER,
    n_dependentes_sf INTEGER,
    opc_fgts BOOLEAN,
    dt_opc_fgts TIMESTAMP WITH TIME ZONE,
    agencia_fgts INTEGER,
    conta_fgts INTEGER,
    dt_exercicio_admissao_ats TIMESTAMP WITH TIME ZONE,
    tipo_adicional_tempo_servico TEXT,
    estabilidade BOOLEAN,
    tipo_conta TEXT,
    numero_conta TEXT NOT NULL,
    digito_conta TEXT NOT NULL,
    probatorio BOOLEAN NOT NULL,
    carga_horaria TEXT,
    tipo_frequencia TEXT,
    dt_ini_situacao_funcional TIMESTAMP WITH TIME ZONE,
    dt_fim_situacao_funcional TIMESTAMP WITH TIME ZONE,
    agencia TEXT NOT NULL,
    ini_contrat_temp TIMESTAMP WITH TIME ZONE,
    fim_contrat_temp TIMESTAMP WITH TIME ZONE,
    dias_afastado INTEGER,
    matricula_destino INTEGER,
    ces_empresa_destino TEXT,
    dado_cadastral_complementar_id BIGINT,
    centro_custo_id BIGINT,
    secao INTEGER,
    zona INTEGER,
    telefone_comercial TEXT,
    uf_trabalho_id BIGINT,
    classificacao_ato_id BIGINT,
    serie_ctps TEXT,
    categoria_alistamento TEXT,
    tipo_estabilidade TEXT,
    numero_sus TEXT,
    matricula_vinculo TEXT,
    descricao_vinculo TEXT,
    valor_vinculo DOUBLE PRECISION,
    cargo_id BIGINT,
    faixa_salarial_cargo_id BIGINT,
    referencia_salarial_cargo_id BIGINT,
    faixa_salarial_funcao_id BIGINT,
    referencia_salarial_funcao_id BIGINT,
    operacao TEXT,
    CONSTRAINT pk_funcionario PRIMARY KEY (id)
);

CREATE TABLE dbo.funcionario_anexo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT NOT NULL,
    anexo_id BIGINT NOT NULL,
    CONSTRAINT pk_funcionario_anexo PRIMARY KEY (id)
);

CREATE TABLE dbo.funcionario_exercicio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT NOT NULL,
    classificacao_ato_id BIGINT NOT NULL,
    exercicio TEXT NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    processo TEXT NOT NULL,
    num_diario_oficial TEXT NOT NULL,
    data_diario_oficial DATE NOT NULL,
    numero_ato TEXT NOT NULL,
    ano_ato TEXT NOT NULL,
    data_ato DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_funcionario_exercicio PRIMARY KEY (id)
);

CREATE TABLE dbo.funcionario_vale_transporte (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT NOT NULL,
    quantidade INTEGER NOT NULL,
    vale_transporte_id BIGINT NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_funcionario_vale_transporte PRIMARY KEY (id)
);

CREATE TABLE dbo.funcionario_verba (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT NOT NULL,
    verba_id BIGINT NOT NULL,
    valor DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_funcionario_verba PRIMARY KEY (id)
);

CREATE TABLE dbo.grau_academico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_grau_academico PRIMARY KEY (id)
);

CREATE TABLE dbo.grupo_salarial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_grupo_salarial PRIMARY KEY (id)
);

CREATE TABLE dbo.habilidade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_habilidade PRIMARY KEY (id)
);

CREATE TABLE dbo.historico_contabil (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT
);

CREATE TABLE dbo.licenca_medica (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    funcionario_id BIGINT NOT NULL,
    crm_id BIGINT,
    afastamento_id BIGINT NOT NULL,
    motivo_afastamento_id BIGINT NOT NULL,
    data_inspecao TIMESTAMP WITH TIME ZONE NOT NULL,
    periodo_inicial TIMESTAMP WITH TIME ZONE NOT NULL,
    periodo_final TIMESTAMP WITH TIME ZONE,
    cid_id BIGINT NOT NULL,
    CONSTRAINT pk_licenca_medica PRIMARY KEY (id)
);

CREATE TABLE dbo.licenca_premio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_exercicio_id BIGINT NOT NULL,
    observacao TEXT NOT NULL,
    data_inicio DATE NOT NULL,
    data_retorno DATE NOT NULL,
    dias TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_licenca_premio PRIMARY KEY (id)
);

CREATE TABLE dbo.lotacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao TEXT NOT NULL,
    descricao_completa TEXT NOT NULL,
    nivel INTEGER,
    efetivo INTEGER,
    id_centro_custo BIGINT,
    tipo_conta TEXT,
    numero_conta INTEGER,
    tipo TEXT,
    vigencia_inicial TIMESTAMP WITH TIME ZONE,
    vigencia_final TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    excluida BOOLEAN,
    CONSTRAINT pk_lotacao PRIMARY KEY (id)
);

CREATE TABLE dbo.lotacao_cargo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    empresa_filial_id BIGINT NOT NULL,
    lotacao_id BIGINT NOT NULL,
    cargo_id BIGINT NOT NULL,
    quant_permitido BIGINT NOT NULL,
    CONSTRAINT pk_lotacao_cargo PRIMARY KEY (id)
);

CREATE TABLE dbo.lotacao_funcao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    empresa_filial_id BIGINT NOT NULL,
    lotacao_id BIGINT NOT NULL,
    funcao_id BIGINT NOT NULL,
    quant_permitido BIGINT NOT NULL,
    CONSTRAINT pk_lotacao_funcao PRIMARY KEY (id)
);

CREATE TABLE dbo.menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    ativo BOOLEAN,
    categoria TEXT,
    nome TEXT NOT NULL,
    url TEXT,
    CONSTRAINT pk_menu PRIMARY KEY (id)
);

CREATE TABLE dbo.modelo_documento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao TEXT NOT NULL,
    conteudo TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_modelo_documento PRIMARY KEY (id)
);

CREATE TABLE dbo.motivo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao TEXT NOT NULL,
    tipo TEXT,
    evento TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_motivo PRIMARY KEY (id)
);

CREATE TABLE dbo.motivo_afastamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo INTEGER NOT NULL,
    descricao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_motivo_afastamento PRIMARY KEY (id)
);

CREATE TABLE dbo.motivo_desligamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_motivo_desligamento PRIMARY KEY (id)
);

CREATE TABLE dbo.motor_calculo_regra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_processamento_id BIGINT NOT NULL,
    verba_id BIGINT NOT NULL,
    descricao TEXT NOT NULL,
    vigencia_inicial TIMESTAMP WITH TIME ZONE NOT NULL,
    vigencia_final TIMESTAMP WITH TIME ZONE NOT NULL,
    rotina TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_motor_calculo_regra PRIMARY KEY (id)
);

CREATE TABLE dbo.municipio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao TEXT NOT NULL,
    cep TEXT NOT NULL,
    naturalidade TEXT NOT NULL,
    regiao_fiscal TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    id_unidade_federativa BIGINT,
    CONSTRAINT pk_municipio PRIMARY KEY (id)
);
