-- ============================================================
-- Worker A Core DDL: tables chunk 1
-- Schema: dbo
-- Tables: 51
-- Range: acidente_trabalho .. dia_util
-- Includes columns, defaults, NOT NULL, identity, primary keys, and unique constraints.
-- ============================================================

CREATE TABLE dbo.acidente_trabalho (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    aviso TEXT NOT NULL,
    causa TEXT NOT NULL,
    data_emissao_documento TIMESTAMP WITH TIME ZONE,
    data_hora_acidente TIMESTAMP WITH TIME ZONE NOT NULL,
    data_previsa_volta TIMESTAMP WITH TIME ZONE NOT NULL,
    dias_afastado INTEGER NOT NULL,
    documento_emitido BOOLEAN,
    numero_cat INTEGER NOT NULL,
    resultado TEXT,
    setor_local TEXT NOT NULL,
    id_anexo BIGINT,
    entidade_id BIGINT,
    funcionario_id BIGINT NOT NULL,
    tomador_servido_id BIGINT,
    CONSTRAINT pk_acidente_trabalho PRIMARY KEY (id)
);

CREATE TABLE dbo.adiantamento_pagamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT NOT NULL,
    empresa_filial_id BIGINT NOT NULL,
    lotacao_id BIGINT NOT NULL,
    tipo_adiantamento TEXT NOT NULL,
    recebimento TEXT NOT NULL,
    valor_adiantamento NUMERIC(13,3) NOT NULL,
    percentual_adiantamento DOUBLE PRECISION NOT NULL,
    data_inicio TIMESTAMP WITH TIME ZONE NOT NULL,
    data_fim TIMESTAMP WITH TIME ZONE,
    status TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    competencia TEXT,
    CONSTRAINT pk_adiantamento_pagamento PRIMARY KEY (id)
);

CREATE TABLE dbo.afastamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    rais_situacao INTEGER,
    rais INTEGER,
    tipo TEXT,
    modalidade TEXT,
    qtd_dias INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    id_motivo_afastamento BIGINT,
    id_motivo_desligamento BIGINT,
    id_causa_afastamento BIGINT,
    CONSTRAINT pk_afastamento PRIMARY KEY (id)
);

CREATE TABLE dbo.agencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    bloqueado BOOLEAN,
    digito INTEGER,
    nome TEXT NOT NULL,
    numero INTEGER NOT NULL,
    referencia TEXT,
    banco_id BIGINT,
    unidade_federativa_id BIGINT NOT NULL,
    municipio_id BIGINT NOT NULL,
    CONSTRAINT pk_agencia PRIMARY KEY (id)
);

CREATE TABLE dbo.aliquota (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    valor_inicial DOUBLE PRECISION NOT NULL,
    valor_final DOUBLE PRECISION,
    deducao DOUBLE PRECISION,
    aliquota DOUBLE PRECISION NOT NULL,
    ano INTEGER NOT NULL,
    faixa TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_aliquota PRIMARY KEY (id)
);

CREATE TABLE dbo.anexo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    description TEXT,
    file_download_uri TEXT,
    file_name TEXT,
    file_type TEXT NOT NULL,
    size BIGINT NOT NULL,
    CONSTRAINT pk_anexo PRIMARY KEY (id)
);

CREATE TABLE dbo.anexo_processo (
    processo_id BIGINT NOT NULL,
    anexo_id BIGINT NOT NULL,
    CONSTRAINT pk_anexo_processo PRIMARY KEY (processo_id, anexo_id)
);

CREATE TABLE dbo.area_formacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    area_formacao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_area_formacao PRIMARY KEY (id)
);

CREATE TABLE dbo.atividade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    observacao TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_atividade PRIMARY KEY (id)
);

CREATE TABLE dbo.atributo_formula (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label TEXT NOT NULL,
    path TEXT NOT NULL,
    CONSTRAINT pk_atributo_formula PRIMARY KEY (id)
);

CREATE TABLE dbo.avaliacao_cargo (
    avaliacao_id BIGINT NOT NULL,
    cargo_id BIGINT NOT NULL
);

CREATE TABLE dbo.avaliacao_desempenho (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cod_avaliacao TEXT NOT NULL,
    nome TEXT NOT NULL,
    modelo TEXT NOT NULL,
    empresa_filial_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_avaliacao_desempenho PRIMARY KEY (id)
);

CREATE TABLE dbo.avaliacao_funcao (
    avaliacao_id BIGINT NOT NULL,
    funcao_id BIGINT NOT NULL
);

CREATE TABLE dbo.avaliacao_lotacao (
    avaliacao_id BIGINT NOT NULL,
    lotacao_id BIGINT NOT NULL
);

CREATE TABLE dbo.banco (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    bloqueado BOOLEAN,
    codigo TEXT NOT NULL,
    nome TEXT NOT NULL,
    principal BOOLEAN,
    CONSTRAINT pk_banco PRIMARY KEY (id)
);

CREATE TABLE dbo.cargo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    descricao TEXT,
    extinto_em TIMESTAMP WITH TIME ZONE,
    nome TEXT NOT NULL,
    cbo_id BIGINT,
    natureza_funcao_id BIGINT,
    processo_funcao_id BIGINT,
    categoria_profissional_id BIGINT,
    sindicato_id BIGINT,
    contagem_tempo_especial TEXT,
    motivo_lei TEXT,
    dedicacao_exclusiva BOOLEAN,
    lei_respaldo TEXT,
    grupo_salarial_id BIGINT,
    CONSTRAINT pk_cargo PRIMARY KEY (id)
);

CREATE TABLE dbo.cargo_atividade (
    cargo_id BIGINT NOT NULL,
    atividade_id BIGINT NOT NULL,
    CONSTRAINT pk_cargo_atividade PRIMARY KEY (cargo_id, atividade_id)
);

CREATE TABLE dbo.cargo_curso (
    cargo_id BIGINT NOT NULL,
    curso_id BIGINT NOT NULL,
    CONSTRAINT pk_cargo_curso PRIMARY KEY (cargo_id, curso_id)
);

CREATE TABLE dbo.cargo_habilidade (
    cargo_id BIGINT NOT NULL,
    habilidade_id BIGINT NOT NULL,
    CONSTRAINT pk_cargo_habilidade PRIMARY KEY (cargo_id, habilidade_id)
);

CREATE TABLE dbo.cargo_verba (
    cargo_id BIGINT NOT NULL,
    verba_id BIGINT NOT NULL,
    CONSTRAINT pk_cargo_verba PRIMARY KEY (cargo_id, verba_id)
);

CREATE TABLE dbo.cargo_vinculo (
    cargo_id BIGINT NOT NULL,
    vinculo_id BIGINT NOT NULL,
    CONSTRAINT pk_cargo_vinculo PRIMARY KEY (cargo_id, vinculo_id)
);

CREATE TABLE dbo.categoria_doenca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    codigo TEXT,
    ativo BOOLEAN,
    descricao TEXT NOT NULL,
    CONSTRAINT pk_categoria_doenca PRIMARY KEY (id)
);

CREATE TABLE dbo.categoria_economica (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_categoria_economica PRIMARY KEY (id)
);

CREATE TABLE dbo.categoria_profissional (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    CONSTRAINT pk_categoria_profissional PRIMARY KEY (id)
);

CREATE TABLE dbo.categoria_profissional_verba (
    categoria_profissional_id BIGINT NOT NULL,
    verba_id BIGINT NOT NULL
);

CREATE TABLE dbo.causa_afastamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_causa_afastamento PRIMARY KEY (id)
);

CREATE TABLE dbo.cbo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    codigo TEXT NOT NULL,
    nome TEXT NOT NULL,
    CONSTRAINT pk_cbo PRIMARY KEY (id)
);

CREATE TABLE dbo.centro_custo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    efetivo INTEGER,
    nivel INTEGER,
    tipo_debito TEXT,
    tipo_credito TEXT,
    conta_credito INTEGER,
    conta_debito INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    tipo_centro_custo TEXT,
    cnpj TEXT,
    CONSTRAINT pk_centro_custo PRIMARY KEY (id)
);

CREATE TABLE dbo.classe_salarial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome TEXT NOT NULL,
    id_grupo_salarial BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_classe_salarial PRIMARY KEY (id)
);

CREATE TABLE dbo.classificacao_agente_nocivo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    tempo_exposicao INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_classificacao_agente_nocivo PRIMARY KEY (id)
);

CREATE TABLE dbo.classificacao_ato (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_classificacao_ato PRIMARY KEY (id)
);

CREATE TABLE dbo.classificacao_internacional_doenca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    categoria_doenca_id BIGINT,
    sub_categoria_doenca_id BIGINT,
    CONSTRAINT pk_classificacao_internacional_doenca PRIMARY KEY (id)
);

CREATE TABLE dbo.cnae (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    codigo_secao TEXT NOT NULL,
    nome_secao TEXT NOT NULL,
    codigo_classe BIGINT NOT NULL,
    nome_classe TEXT NOT NULL,
    CONSTRAINT pk_cnae PRIMARY KEY (id)
);

CREATE TABLE dbo.codigo_pagamento_gps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_codigo_pagamento_gps PRIMARY KEY (id)
);

CREATE TABLE dbo.codigo_recolhimento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo INTEGER NOT NULL,
    descricao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_codigo_recolhimento PRIMARY KEY (id)
);

CREATE TABLE dbo.compensacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tomador_servico_id BIGINT NOT NULL,
    competencia TIMESTAMP WITH TIME ZONE NOT NULL,
    valor_compensacao DOUBLE PRECISION NOT NULL,
    data_compensacao_inicial TIMESTAMP WITH TIME ZONE,
    data_compensacao_final TIMESTAMP WITH TIME ZONE,
    campo_seis_gps_anterior INTEGER,
    campo_nove_gps_anterior INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_compensacao PRIMARY KEY (id)
);

CREATE TABLE dbo.consignado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao TEXT NOT NULL,
    telefone TEXT,
    id_centro_custo BIGINT NOT NULL,
    estado TEXT,
    cidade TEXT,
    cep TEXT,
    logradouro TEXT,
    complemento TEXT,
    numero TEXT,
    bairro TEXT,
    cnpj TEXT NOT NULL,
    rg TEXT,
    orgao_expedidor TEXT,
    margem_consignavel DOUBLE PRECISION,
    id_banco BIGINT,
    agencia INTEGER,
    conta_corrente TEXT,
    contrato TEXT,
    tipo_calculo DOUBLE PRECISION,
    email TEXT,
    taxa_operacional DOUBLE PRECISION,
    tac DOUBLE PRECISION,
    taxa_cadastro_sigla_consignado INTEGER,
    sigla_consignado TEXT,
    registro_ans INTEGER,
    codigo_convergencia INTEGER,
    digito_convergencia INTEGER,
    extrato_convenente INTEGER,
    digito_convenente INTEGER,
    nome_convenente TEXT,
    pv_responsavel TEXT,
    dt_competencia_processamento TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    verba_desconto INTEGER,
    modalidade TEXT,
    id_unidade_federativa_consignatario BIGINT,
    CONSTRAINT pk_consignado PRIMARY KEY (id)
);

CREATE TABLE dbo.conta_contabil (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    empresa_id BIGINT,
    filial_id BIGINT,
    centro_custo_id BIGINT,
    tipo_conta TEXT NOT NULL,
    conta INTEGER NOT NULL,
    rateio DOUBLE PRECISION NOT NULL,
    rateio_total DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    id_verba BIGINT,
    CONSTRAINT pk_conta_contabil PRIMARY KEY (id)
);

CREATE TABLE dbo.conta_contabil_lotacao (
    conta_contabil_id BIGINT NOT NULL,
    lotacao_id BIGINT NOT NULL,
    CONSTRAINT pk_conta_contabil_lotacao PRIMARY KEY (conta_contabil_id, lotacao_id)
);

CREATE TABLE dbo.conta_contabil_simples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_conta_contabil_simples PRIMARY KEY (id)
);

CREATE TABLE dbo.contribuicao_sindical (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    funcionario_id BIGINT NOT NULL,
    sindicato_id BIGINT NOT NULL,
    permite_desconto BOOLEAN DEFAULT FALSE,
    anexo_id BIGINT,
    ano INTEGER NOT NULL,
    CONSTRAINT pk_contribuicao_sindical PRIMARY KEY (id)
);

CREATE TABLE dbo.convenio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_convenio PRIMARY KEY (id)
);

CREATE TABLE dbo.correcao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dt_competencia TIMESTAMP WITH TIME ZONE NOT NULL,
    tipo_processamento_id BIGINT NOT NULL,
    empresa_id BIGINT,
    filial_id BIGINT,
    lotacao_id BIGINT,
    centro_custo_id BIGINT,
    sindicato_id BIGINT,
    funcao_id BIGINT,
    nivel_salarial_id BIGINT,
    situacao_afastamento_id BIGINT,
    tipo_folha_id BIGINT,
    verba_id BIGINT,
    valor_faixa_I NUMERIC(13,3),
    valor_faixa_II NUMERIC(13,3),
    percentual_produto DOUBLE PRECISION,
    percentual_aumento DOUBLE PRECISION,
    valor_produto NUMERIC(13,3),
    valor_piso NUMERIC(13,3),
    tipo_arredondamento INTEGER,
    avos INTEGER,
    valor_arrendamento NUMERIC(13,3),
    atualiza_mes INTEGER,
    retroativo TIMESTAMP WITH TIME ZONE,
    abono BOOLEAN,
    verba_abono INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_correcao PRIMARY KEY (id)
);

CREATE TABLE dbo.crm_crea (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    coordenador_pcmso BOOLEAN,
    nome_conveniado TEXT NOT NULL,
    numero_crm_crea TEXT NOT NULL,
    responsavel_ltcat BOOLEAN,
    tipo TEXT NOT NULL,
    CONSTRAINT pk_crm_crea PRIMARY KEY (id)
);

CREATE TABLE dbo.crm_crea_convenio (
    crm_crea_id BIGINT NOT NULL,
    convenio_id BIGINT NOT NULL,
    CONSTRAINT pk_crm_crea_convenio PRIMARY KEY (crm_crea_id, convenio_id)
);

CREATE TABLE dbo.curso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_curso TEXT NOT NULL,
    codigo_mec TEXT NOT NULL,
    id_grau_academico BIGINT NOT NULL,
    id_area_formacao BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    carga_horaria BIGINT NOT NULL,
    CONSTRAINT pk_curso PRIMARY KEY (id)
);

CREATE TABLE dbo.dado_cadastral_complementar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT NOT NULL,
    fardamento TEXT,
    altura DOUBLE PRECISION,
    peso DOUBLE PRECISION,
    calcado TEXT,
    condicao_retorno_trabalho TEXT NOT NULL,
    dt_ini_deficiencia TIMESTAMP WITH TIME ZONE,
    dt_fim_deficiencia TIMESTAMP WITH TIME ZONE,
    reabilitado BOOLEAN NOT NULL,
    cotista BOOLEAN NOT NULL,
    descricao_deficiencia TEXT,
    dt_aposentadoria TIMESTAMP WITH TIME ZONE NOT NULL,
    tipo_aposentadoria TEXT NOT NULL,
    proporcionalidade INTEGER,
    tipo_proporcao TEXT NOT NULL,
    contribuicao_inss BOOLEAN NOT NULL,
    consignado_bloqueado BOOLEAN,
    contribuicao_ir BOOLEAN NOT NULL,
    num_processo_aposentadoria BIGINT,
    local_redistribuicao TEXT,
    dt_distribuicao_cedencia TIMESTAMP WITH TIME ZONE,
    dt_ini_isencao_ir_previdencia TIMESTAMP WITH TIME ZONE,
    dt_fim_isencao_ir_previdencia TIMESTAMP WITH TIME ZONE,
    dt_falecimento TIMESTAMP WITH TIME ZONE,
    tempo_servidor_professor INTEGER,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    em_processo_de_aposentadoria BOOLEAN DEFAULT FALSE,
    CONSTRAINT pk_dado_cadastral_complementar PRIMARY KEY (id)
);

CREATE TABLE dbo.definicao_de_organico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT NOT NULL,
    vigencia_inicial DATE,
    vigencia_final DATE,
    email_responsavel TEXT NOT NULL,
    primeiro_substituto_nome TEXT,
    primeiro_substituto_email TEXT,
    segundo_substituto_nome TEXT,
    segundo_substituto_email TEXT,
    previsao_funcionarios BIGINT,
    funcionarios_atuais BIGINT,
    total_funcionarios BIGINT,
    previsao_custos NUMERIC(13,3),
    custos_atuais NUMERIC(13,3),
    custo_total NUMERIC(13,3),
    conf_critica_avisar BOOLEAN,
    conf_critica_criticar BOOLEAN,
    conf_critica_nenhum BOOLEAN,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    empresa_filial_id BIGINT NOT NULL,
    CONSTRAINT pk_definicao_de_organico PRIMARY KEY (id)
);

CREATE TABLE dbo.dependente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT NOT NULL,
    tipo TEXT NOT NULL,
    nome TEXT NOT NULL,
    naturalidade TEXT,
    inicio_motivo DATE,
    fim_motivo DATE,
    sexo TEXT NOT NULL,
    dt_nascimento DATE,
    num_cpf TEXT,
    num_identidade TEXT,
    logradouro TEXT,
    numero TEXT,
    municipio_id BIGINT NOT NULL,
    unidade_federativa_id BIGINT NOT NULL,
    cep TEXT,
    num_documento_comprobatorio TEXT,
    dt_documento_comprobatorio DATE,
    dependencia_ir BOOLEAN,
    dependencia_sf BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_dependente PRIMARY KEY (id)
);

CREATE TABLE dbo.dependente_beneficio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    consignado_id BIGINT NOT NULL,
    dependente_id BIGINT NOT NULL,
    valor NUMERIC(13,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_dependente_beneficio PRIMARY KEY (id)
);

CREATE TABLE dbo.dia_util (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ano TEXT NOT NULL,
    mes TEXT NOT NULL,
    dia TEXT NOT NULL,
    dia_da_semana TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT
);
