-- ============================================================
-- Worker A Core DDL: tables chunk 3
-- Schema: dbo
-- Tables: 50
-- Range: nacionalidade .. vinculo_verba
-- Includes columns, defaults, NOT NULL, identity, primary keys, and unique constraints.
-- ============================================================

CREATE TABLE dbo.nacionalidade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sigla TEXT NOT NULL,
    nacionalidade_feminina TEXT NOT NULL,
    nacionalidade_masculina TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_nacionalidade PRIMARY KEY (id)
);

CREATE TABLE dbo.natureza_funcao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_natureza_funcao PRIMARY KEY (id)
);

CREATE TABLE dbo.natureza_juridica (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    nome TEXT NOT NULL,
    grupamento TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_natureza_juridica PRIMARY KEY (id)
);

CREATE TABLE dbo.nivel_salarial_historico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    data_ajuste TIMESTAMP WITH TIME ZONE NOT NULL,
    origem_ajuste TEXT NOT NULL,
    valor_ajustado DOUBLE PRECISION NOT NULL,
    valor_original DOUBLE PRECISION NOT NULL,
    valor_retroativo DOUBLE PRECISION,
    nivel_salarial_id BIGINT,
    simulador_nivel_salarial_id BIGINT,
    CONSTRAINT pk_nivel_salarial_historico PRIMARY KEY (id)
);

CREATE TABLE dbo.notificacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    descricao TEXT NOT NULL,
    envia_email BOOLEAN,
    id_entidade BIGINT,
    tipo_notificacao TEXT NOT NULL,
    visualizada BOOLEAN,
    id_usuario_destinatario BIGINT,
    CONSTRAINT pk_notificacao PRIMARY KEY (id)
);

CREATE TABLE dbo.papel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome TEXT,
    id_menu BIGINT,
    CONSTRAINT pk_papel PRIMARY KEY (id)
);

CREATE TABLE dbo.pensao_alimenticia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    funcionario_id BIGINT NOT NULL,
    nome_alimentando TEXT,
    nascimento_alimentando TIMESTAMP WITH TIME ZONE,
    tipo_pensao TEXT,
    logradouro TEXT,
    numero BIGINT,
    complemento TEXT,
    bairro TEXT,
    uf_id BIGINT,
    municipio_id BIGINT,
    cep BIGINT,
    rg BIGINT,
    orgao TEXT,
    uf_documento_id BIGINT,
    cpf BIGINT,
    ddd BIGINT,
    numero_telefone BIGINT,
    responsavel_id BIGINT,
    numero_processo_responsavel BIGINT,
    numero_processo_pagamento BIGINT,
    data_inicial TIMESTAMP WITH TIME ZONE,
    data_final TIMESTAMP WITH TIME ZONE,
    centro_custo_id BIGINT,
    verba_id BIGINT,
    data_inicial_pagamento TIMESTAMP WITH TIME ZONE,
    data_final_pagamento TIMESTAMP WITH TIME ZONE,
    tipo_conta TEXT,
    banco_id BIGINT,
    conta BIGINT,
    vencimento TIMESTAMP WITH TIME ZONE,
    tipo_desconto TEXT,
    valor DOUBLE PRECISION,
    salario_familia BIGINT,
    incidencia_principal TEXT,
    salario_13 BOOLEAN DEFAULT FALSE,
    ferias BOOLEAN DEFAULT FALSE,
    recisao BOOLEAN DEFAULT FALSE,
    agencia_id BIGINT,
    CONSTRAINT pk_pensao_alimenticia PRIMARY KEY (id)
);

CREATE TABLE dbo.prestador_servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_civil TEXT NOT NULL,
    nome_social TEXT,
    cpf TEXT NOT NULL,
    dt_nascimento TIMESTAMP WITH TIME ZONE NOT NULL,
    estado_civil TEXT NOT NULL,
    sexo TEXT NOT NULL,
    cor TEXT,
    nacionalidade_id BIGINT NOT NULL,
    nome_mae TEXT NOT NULL,
    nome_pai TEXT,
    logradouro TEXT NOT NULL,
    numero TEXT NOT NULL,
    complemento TEXT,
    bairro TEXT,
    uf_id_endereco BIGINT NOT NULL,
    municipio_prestador_id BIGINT NOT NULL,
    cep TEXT NOT NULL,
    ddd_celular INTEGER NOT NULL,
    numero_celular TEXT NOT NULL,
    ddd_telefone INTEGER,
    telefone TEXT,
    email TEXT,
    locacao TEXT NOT NULL,
    empresa_filial_id BIGINT,
    categoria_prestador_id BIGINT NOT NULL,
    cbo_prestador_id BIGINT NOT NULL,
    dt_inicial TIMESTAMP WITH TIME ZONE,
    dt_final TIMESTAMP WITH TIME ZONE,
    unidade_pgto_fixo TEXT,
    natureza_atividade TEXT,
    agente_nocivo BOOLEAN,
    exposicao_passado BOOLEAN,
    tempo_contribuicao TEXT,
    recolhe_inss BOOLEAN,
    modo_pagamento TEXT,
    valor_pago DOUBLE PRECISION,
    desconto_inss DOUBLE PRECISION,
    base_calculo DOUBLE PRECISION,
    desconto_ir DOUBLE PRECISION,
    registro_fgts TEXT,
    cnpj TEXT,
    ir_retido DOUBLE PRECISION,
    inss_pago DOUBLE PRECISION,
    cnpj_empresa_pagadora TEXT NOT NULL,
    dia_pagamento INTEGER NOT NULL,
    verba_id BIGINT,
    convenio_id BIGINT,
    numero_empenho INTEGER,
    dt_empenho TIMESTAMP WITH TIME ZONE,
    numero_nf INTEGER,
    dt_emissao_nf TIMESTAMP WITH TIME ZONE,
    pis_pasep TEXT,
    numero_ctps INTEGER NOT NULL,
    serie_ctps INTEGER NOT NULL,
    uf_id_ctps BIGINT NOT NULL,
    numero_ident_civil_nac INTEGER,
    org_emissor_ident_civil_nac TEXT,
    dt_emissao_ident_civil_nac TIMESTAMP WITH TIME ZONE,
    numero_rg INTEGER NOT NULL,
    orgao_emissor_rg TEXT NOT NULL,
    dt_emissao_rg TIMESTAMP WITH TIME ZONE NOT NULL,
    num_reg_nac_estrangeiro INTEGER,
    org_emissor_reg_nac_estrangeiro TEXT,
    dt_emissao_reg_nac_estrangeiro TIMESTAMP WITH TIME ZONE,
    registro_profissional INTEGER,
    dt_emissao_reg_profissional TIMESTAMP WITH TIME ZONE,
    dt_validade_reg_profissional TIMESTAMP WITH TIME ZONE,
    numero_cnh INTEGER,
    dt_validade_cnh TIMESTAMP WITH TIME ZONE,
    dt_primeira_cnh TIMESTAMP WITH TIME ZONE,
    dt_emissao_cnh TIMESTAMP WITH TIME ZONE,
    categoria_cnh TEXT,
    uf_id_cnh BIGINT,
    tipo_dependente TEXT,
    nome_dependente TEXT,
    cpf_dependente TEXT,
    imposto_retido_fonte BOOLEAN,
    plano_saude_privado BOOLEAN,
    recebe_beneficio BOOLEAN,
    capacitacao_profissional BOOLEAN,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_prestador_servico PRIMARY KEY (id)
);

CREATE TABLE dbo.processo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT NOT NULL,
    numero_processo TEXT NOT NULL,
    assunto TEXT NOT NULL,
    data_inicio TIMESTAMP WITH TIME ZONE NOT NULL,
    data_fim TIMESTAMP WITH TIME ZONE,
    requerente TEXT,
    situacao TEXT,
    ato_portaria BIGINT,
    data_ato TIMESTAMP WITH TIME ZONE,
    doe TEXT,
    data_doe TIMESTAMP WITH TIME ZONE,
    impacto_financeiro BOOLEAN NOT NULL,
    tipo_reflexo TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    inicio_impacto_financeiro TIMESTAMP WITH TIME ZONE,
    fim_impacto_financeiro TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_processo PRIMARY KEY (id)
);

CREATE TABLE dbo.processo_funcao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_processo_funcao PRIMARY KEY (id)
);

CREATE TABLE dbo.recisao_contrato (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT NOT NULL,
    ferias_vencidas BOOLEAN NOT NULL,
    aviso_previo BOOLEAN NOT NULL,
    data_aviso TIMESTAMP WITH TIME ZONE,
    dias_aviso INTEGER,
    data_desligamento TIMESTAMP WITH TIME ZONE NOT NULL,
    data_homologacao TIMESTAMP WITH TIME ZONE,
    data_pagamento TIMESTAMP WITH TIME ZONE,
    status TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    motivo_id BIGINT NOT NULL,
    CONSTRAINT pk_recisao_contrato PRIMARY KEY (id)
);

CREATE TABLE dbo.referencia_salarial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    valor DOUBLE PRECISION NOT NULL,
    nivel_referencia BOOLEAN,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    mes_ano_competencia TEXT,
    CONSTRAINT pk_referencia_salarial PRIMARY KEY (id)
);

CREATE TABLE dbo.regra_aposentadoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    abono_permanencia BOOLEAN,
    artigo TEXT,
    idade_homem INTEGER,
    idade_mulher INTEGER,
    lei_base TEXT NOT NULL,
    licenca_premio BOOLEAN,
    modalidade_aposentadoria TEXT NOT NULL,
    modalidade_aposentadoria_nome TEXT,
    pedagio BOOLEAN,
    tempo_cargo_efetivo_homem INTEGER,
    tempo_cargo_efetivo_mulher INTEGER,
    tempo_carreira INTEGER,
    tempo_contribuicao_homem INTEGER,
    tempo_contribuicao_mulher INTEGER,
    tempo_servico_publico INTEGER,
    tipo_aposentadoria TEXT,
    tipo_regra TEXT,
    vigencia TIMESTAMP WITH TIME ZONE NOT NULL,
    proventos TEXT,
    tipo_vigencia TEXT,
    idade_homem_formula TEXT,
    idade_mulher_formula TEXT,
    tempo_contribuicao_homem_formula TEXT,
    tempo_contribuicao_mulher_formula TEXT,
    tempo_servico_em_pleno_exercicio BOOLEAN,
    CONSTRAINT pk_regra_aposentadoria PRIMARY KEY (id)
);

CREATE TABLE dbo.requisicao_pessoal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    solicitante_id BIGINT NOT NULL,
    justificativa TEXT NOT NULL,
    situacao TEXT NOT NULL,
    data_entrada TIMESTAMP WITH TIME ZONE NOT NULL,
    data_limite TIMESTAMP WITH TIME ZONE NOT NULL,
    funcionario_substituido_id BIGINT,
    motivo_solicitacao TEXT NOT NULL,
    data_prevista_adimissao TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    data_conclusao TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_requisicao_pessoal PRIMARY KEY (id)
);

CREATE TABLE dbo.requisicao_pessoal_candidato (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome TEXT NOT NULL,
    comentario TEXT,
    comentario_curriculo TEXT,
    situacao TEXT NOT NULL,
    id_anexo BIGINT NOT NULL,
    id_req_pessoal BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_requisicao_pessoal_candidato PRIMARY KEY (id)
);

CREATE TABLE dbo.requisicao_pessoal_funcao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcao_id BIGINT NOT NULL,
    tipo_contratacao TEXT NOT NULL,
    qtd_vagas INTEGER NOT NULL,
    custo_por_vaga DOUBLE PRECISION NOT NULL,
    turno_id BIGINT NOT NULL,
    requisicao_pessoal_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_requisicao_pessoal_funcao PRIMARY KEY (id)
);

CREATE TABLE dbo.requisito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao TEXT NOT NULL,
    dado_comparativo TEXT NOT NULL,
    comparacao TEXT NOT NULL,
    valor TEXT,
    inicio_intervalo TEXT,
    fim_intervalo TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_requisito PRIMARY KEY (id)
);

CREATE TABLE dbo.responsavel_legal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo_responsavel TEXT NOT NULL,
    nome TEXT NOT NULL,
    id_banco BIGINT NOT NULL,
    agencia INTEGER NOT NULL,
    conta_corrente INTEGER NOT NULL,
    tipo_responsavel TEXT NOT NULL,
    cpf TEXT NOT NULL,
    identidade INTEGER NOT NULL,
    tipo_conta TEXT NOT NULL,
    logradouro TEXT NOT NULL,
    numero TEXT NOT NULL,
    complemento TEXT NOT NULL,
    bairro TEXT NOT NULL,
    id_municipio BIGINT NOT NULL,
    cep TEXT NOT NULL,
    id_unidade_federativa BIGINT NOT NULL,
    telefone TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_responsavel_legal PRIMARY KEY (id)
);

CREATE TABLE dbo.sefip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    tipo TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_sefip PRIMARY KEY (id)
);

CREATE TABLE dbo.simulador_nivel_salarial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao TEXT NOT NULL,
    data_competencia TIMESTAMP WITH TIME ZONE,
    situacao TEXT,
    programar_ajuste BOOLEAN,
    motivo_ajuste TEXT NOT NULL,
    tipo_ajuste TEXT NOT NULL,
    valor_ajuste DOUBLE PRECISION NOT NULL,
    data_ajuste TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_simulador_nivel_salarial PRIMARY KEY (id)
);

CREATE TABLE dbo.simulador_nivel_salarial_acordo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    simulador_id BIGINT NOT NULL,
    tipo_acordo TEXT NOT NULL,
    data_acordo TIMESTAMP WITH TIME ZONE,
    data_incial TIMESTAMP WITH TIME ZONE NOT NULL,
    data_final TIMESTAMP WITH TIME ZONE NOT NULL,
    descricao TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_simulador_nivel_salarial_acordo PRIMARY KEY (id)
);

CREATE TABLE dbo.simulador_nivel_salarial_valores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nivel_salarial_id BIGINT NOT NULL,
    simulador_id BIGINT NOT NULL,
    valor_ajustado DOUBLE PRECISION NOT NULL,
    valor_retroativo DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_simulador_nivel_salarial_valores PRIMARY KEY (id)
);

CREATE TABLE dbo.sindicato (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao TEXT NOT NULL,
    mes_base INTEGER NOT NULL,
    piso_salarial INTEGER NOT NULL,
    cnpj TEXT NOT NULL,
    codigo_entidade TEXT NOT NULL,
    ddd INTEGER NOT NULL,
    telefone TEXT NOT NULL,
    patronal TEXT NOT NULL,
    endereco TEXT NOT NULL,
    numero TEXT NOT NULL,
    complemento TEXT NOT NULL,
    bairro TEXT NOT NULL,
    municipio TEXT NOT NULL,
    id_unidade_federativa_sindicato BIGINT NOT NULL,
    cep TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_sindicato PRIMARY KEY (id)
);

CREATE TABLE dbo.situacao_funcional (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT NOT NULL,
    tipo_situacao_funcional TEXT NOT NULL,
    funcao_id BIGINT,
    nivel_salarial_id BIGINT,
    motivo_id BIGINT,
    ato TEXT,
    dt_ato TIMESTAMP WITH TIME ZONE,
    dt_diario_oficial TIMESTAMP WITH TIME ZONE,
    dt_inicio TIMESTAMP WITH TIME ZONE,
    dt_fim TIMESTAMP WITH TIME ZONE,
    dt_retorno TIMESTAMP WITH TIME ZONE,
    obs_cancel TEXT,
    empresa_filial_id BIGINT,
    tipo_exoneracao_demissao TEXT,
    sit_motivo_afastamento_id BIGINT,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_situacao_funcional PRIMARY KEY (id)
);

CREATE TABLE dbo.sol_adiantamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    solicitante BIGINT NOT NULL,
    porcentagem_adiantamento TEXT NOT NULL,
    mes_adiantamento TEXT NOT NULL,
    situacao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_sol_adiantamento PRIMARY KEY (id)
);

CREATE TABLE dbo.sub_categoria_doenca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    CONSTRAINT pk_sub_categoria_doenca PRIMARY KEY (id)
);

CREATE TABLE dbo.sysdiagrams (
    name TEXT NOT NULL,
    principal_id INTEGER NOT NULL,
    diagram_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version INTEGER,
    definition BYTEA,
    CONSTRAINT pk_sysdiagrams PRIMARY KEY (diagram_id),
    CONSTRAINT uq_sysdiagrams__principal_id__name UNIQUE (principal_id, name)
);

CREATE TABLE dbo.tempo_servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    funcionario_id BIGINT NOT NULL,
    protocolo_ctc_cts TEXT NOT NULL,
    salario DOUBLE PRECISION NOT NULL,
    indice_contribuicao TEXT NOT NULL,
    ultimo_cargo TEXT NOT NULL,
    sefip_id BIGINT NOT NULL,
    descricao_certidao TEXT,
    descricao_empresa TEXT NOT NULL,
    tipo_averbacao_id BIGINT NOT NULL,
    tipo_averbacao TEXT NOT NULL,
    averbado BOOLEAN NOT NULL,
    dt_inicio TIMESTAMP WITH TIME ZONE NOT NULL,
    dt_termino TIMESTAMP WITH TIME ZONE NOT NULL,
    qtd_dias INTEGER NOT NULL,
    num_processo TEXT NOT NULL,
    classificacao_ato_id BIGINT NOT NULL,
    num_diario_oficial TEXT NOT NULL,
    ano_publicacao INTEGER NOT NULL,
    dt_diario_oficial TIMESTAMP WITH TIME ZONE NOT NULL,
    num_ato TEXT NOT NULL,
    data TIMESTAMP WITH TIME ZONE NOT NULL,
    endereco TEXT NOT NULL,
    cidade TEXT NOT NULL,
    numero TEXT NOT NULL,
    complemento TEXT,
    bairro TEXT NOT NULL,
    uf_id BIGINT NOT NULL,
    cep TEXT NOT NULL,
    telefone TEXT NOT NULL,
    cnpj TEXT NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_tempo_servico PRIMARY KEY (id)
);

CREATE TABLE dbo.tipo_averbacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo INTEGER NOT NULL,
    descricao TEXT NOT NULL,
    forma_averbacao TEXT NOT NULL,
    deducao_averbacao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_tipo_averbacao PRIMARY KEY (id)
);

CREATE TABLE dbo.tipo_contrato (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    nome TEXT NOT NULL,
    CONSTRAINT pk_tipo_contrato PRIMARY KEY (id)
);

CREATE TABLE dbo.tipo_ferias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao TEXT NOT NULL,
    abono INTEGER NOT NULL,
    dias INTEGER NOT NULL,
    saldo INTEGER NOT NULL,
    decimo_terceiro TEXT NOT NULL,
    coletivo TEXT NOT NULL,
    licenca_premio TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_tipo_ferias PRIMARY KEY (id)
);

CREATE TABLE dbo.tipo_folha (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_tipo_folha PRIMARY KEY (id)
);

CREATE TABLE dbo.tipo_folha_verbas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_tipo_folha BIGINT NOT NULL,
    id_verba BIGINT NOT NULL,
    CONSTRAINT pk_tipo_folha_verbas PRIMARY KEY (id)
);

CREATE TABLE dbo.tipo_processamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    descricao TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_tipo_processamento PRIMARY KEY (id)
);

CREATE TABLE dbo.tomador_servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_inscricao TEXT NOT NULL,
    razao_social TEXT NOT NULL,
    cnpj TEXT NOT NULL,
    id_codigo_pagamento_gps BIGINT,
    id_codigo_recolhimento BIGINT,
    estado TEXT NOT NULL,
    cidade TEXT NOT NULL,
    cep TEXT NOT NULL,
    logradouro TEXT NOT NULL,
    complemento TEXT NOT NULL,
    numero TEXT NOT NULL,
    bairro TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    compensacao_id BIGINT,
    CONSTRAINT pk_tomador_servico PRIMARY KEY (id)
);

CREATE TABLE dbo.transferencia_funcionario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    funcionario_id BIGINT NOT NULL,
    lotacao_id BIGINT,
    empresa_id BIGINT,
    CONSTRAINT pk_transferencia_funcionario PRIMARY KEY (id)
);

CREATE TABLE dbo.treinamento_sugerido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    curso_id BIGINT NOT NULL,
    tipo TEXT NOT NULL,
    instrutor TEXT NOT NULL,
    motivo TEXT NOT NULL,
    local TEXT NOT NULL,
    data_inicio DATE NOT NULL,
    data_final DATE NOT NULL,
    situacao TEXT NOT NULL,
    informacoes_adicionais TEXT,
    turma TEXT,
    justificativa TEXT,
    resultado TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    horario TIMESTAMP WITH TIME ZONE,
    quantidade_vagas TEXT,
    CONSTRAINT pk_treinamento_sugerido PRIMARY KEY (id)
);

CREATE TABLE dbo.treinamento_sugerido_complemento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_treinamento_sugerido BIGINT NOT NULL,
    local TEXT,
    endereco TEXT,
    complemento TEXT,
    bairro TEXT,
    id_municipio BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_treinamento_sugerido_complemento PRIMARY KEY (id)
);

CREATE TABLE dbo.treinamento_sugerido_funcionario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_funcionario BIGINT NOT NULL,
    id_treinamento_sugerido BIGINT NOT NULL,
    CONSTRAINT pk_treinamento_sugerido_funcionario PRIMARY KEY (id)
);

CREATE TABLE dbo.treinamento_sugerido_valores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_treinamento_sugerido BIGINT NOT NULL,
    valor_docencia DOUBLE PRECISION,
    valor_conducao DOUBLE PRECISION,
    valor_diarias DOUBLE PRECISION,
    valor_material DOUBLE PRECISION,
    valor_hospedagem DOUBLE PRECISION,
    valor_individual DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_treinamento_sugerido_valores PRIMARY KEY (id)
);

CREATE TABLE dbo.turno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    data_inicio TIMESTAMP WITH TIME ZONE NOT NULL,
    data_fim TIMESTAMP WITH TIME ZONE NOT NULL,
    horario_flexivel BOOLEAN,
    horario_flexivel_inicio TIMESTAMP WITH TIME ZONE,
    horario_flexivel_fim TIMESTAMP WITH TIME ZONE,
    intervalo_flexivel BOOLEAN,
    intervalo_flexivel_inicio TIMESTAMP WITH TIME ZONE,
    intervalo_flexivel_fim TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    intervalo TIMESTAMP WITH TIME ZONE,
    jornada TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_turno PRIMARY KEY (id)
);

CREATE TABLE dbo.turno_folga (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    turno_id BIGINT NOT NULL,
    dia TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_turno_folga PRIMARY KEY (id)
);

CREATE TABLE dbo.unidade_federativa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sigla TEXT NOT NULL,
    estado TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_unidade_federativa PRIMARY KEY (id)
);

CREATE TABLE dbo.usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    ativo BOOLEAN,
    cpf TEXT,
    email TEXT,
    login TEXT,
    nome TEXT,
    senha TEXT,
    id_anexo BIGINT,
    empresa_filial_id BIGINT,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

CREATE TABLE dbo.usuario_papel (
    usuario_id BIGINT NOT NULL,
    papel_id BIGINT NOT NULL,
    CONSTRAINT pk_usuario_papel PRIMARY KEY (usuario_id, papel_id)
);

CREATE TABLE dbo.vale_transporte (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    valor DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_vale_transporte PRIMARY KEY (id)
);

CREATE TABLE dbo.verba (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo TEXT NOT NULL,
    descricao_verba TEXT NOT NULL,
    descricao_resumida TEXT NOT NULL,
    tipo_verba TEXT NOT NULL,
    destinacao_externa TEXT,
    valor_maximo DOUBLE PRECISION,
    tipo_valor TEXT NOT NULL,
    incidencia_valor TEXT,
    comentario TEXT,
    conta_debito INTEGER,
    conta_credito INTEGER,
    conta_auxiliar_primaria INTEGER,
    conta_auxiliar_secundaria INTEGER,
    vigencia_inicial TIMESTAMP WITH TIME ZONE,
    vigencia_final TIMESTAMP WITH TIME ZONE,
    recorrencia TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    centro_custo_id BIGINT NOT NULL,
    referencia DOUBLE PRECISION,
    CONSTRAINT pk_verba PRIMARY KEY (id)
);

CREATE TABLE dbo.verba_formula (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    formula TEXT NOT NULL,
    descricao TEXT NOT NULL,
    verba_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT pk_verba_formula PRIMARY KEY (id)
);

CREATE TABLE dbo.vinculo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    updated_by BIGINT,
    data_final TIMESTAMP WITH TIME ZONE,
    data_inicial TIMESTAMP WITH TIME ZONE,
    descricao TEXT NOT NULL,
    grupo TEXT NOT NULL,
    categoria_esocial_id BIGINT,
    categoria_sefip_id BIGINT,
    ocorrencia_sefip_id BIGINT,
    situacao_inicial_afastamento_id BIGINT,
    tipo_contrato_id BIGINT,
    vinculo_apos_id BIGINT,
    CONSTRAINT pk_vinculo PRIMARY KEY (id)
);

CREATE TABLE dbo.vinculo_verba (
    vinculo_id BIGINT NOT NULL,
    verba_id BIGINT NOT NULL
);
