import { DatabaseService } from '../../database/database.service';
import { RhRequestDto } from './rh-workflows.dto';
import { RequestRow } from './workflow-types';
import { toIso } from './workflow-utils';

export class WorkflowRequestService {
  constructor(private readonly databaseService: DatabaseService) {}

  async createImportRequest(kind: string, input: RhRequestDto) {
    const code = `RH_IMPORT_${kind.replace(/[^a-z0-9]+/gi, '_').toUpperCase()}`;
    return this.createRequest(
      code,
      `Importacao RH - ${kind}`,
      'PROCESS',
      input,
    );
  }

  async createReportRequest(reportKey: string, input: RhRequestDto) {
    const code = `RH_REPORT_${reportKey.replace(/[^a-z0-9]+/gi, '_').toUpperCase()}`;
    return this.createRequest(
      code,
      `Relatorio RH - ${reportKey}`,
      'GENERATE',
      input,
    );
  }

  private async createRequest(
    code: string,
    name: string,
    kind: 'PROCESS' | 'GENERATE',
    input: RhRequestDto,
  ) {
    const rows = await this.databaseService.query<RequestRow>(
      `
      WITH definition AS (
        INSERT INTO public.report_definition (tenant_id, code, module_key, name, description, status)
        VALUES (public.sgp_current_tenant_uuid(), $1, 'rh', $2, $3, 'ACTIVE'::"RecordStatus")
        ON CONFLICT (tenant_id, code) DO UPDATE SET name = EXCLUDED.name, updated_at = now()
        RETURNING id
      )
      INSERT INTO public.report_request (definition_id, competence_year, competence_month, status, parameters)
      SELECT id, $4, $5, 'REQUESTED'::"ReportRequestStatus", $6::jsonb
      FROM definition
      RETURNING id, status::text, requested_at
      `,
      [
        code,
        name,
        `${kind} request generated by RH workflow`,
        input.year ?? null,
        input.month ?? null,
        JSON.stringify({
          ...input.parameters,
          employeeId: input.employeeId,
          sourceFileName: input.sourceFileName,
          requestKind: kind,
        }),
      ],
    );
    const row = rows[0]!;
    return {
      id: row.id,
      status: row.status,
      requestedAt: toIso(row.requested_at),
    };
  }
}
