import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

interface PermissionSeed {
  permissions: Array<{
    key: string;
    moduleKey: string;
    resourceKey: string;
    actionKey: string;
    routePattern?: string;
  }>;
}

const scriptDir = dirname(fileURLToPath(import.meta.url));
const sourceRoot = resolve(scriptDir, '..');
const seedPath = resolve(sourceRoot, 'database/seed/permission-catalog.json');
const backendCatalogPath = resolve(
  sourceRoot,
  'backend/src/iam/permissions/permission-catalog.generated.ts',
);
const frontendCatalogPath = resolve(
  sourceRoot,
  'frontend/src/app/core/navigation/route-permission-map.generated.ts',
);

function readSeed(): PermissionSeed {
  const parsed = JSON.parse(readFileSync(seedPath, 'utf8')) as PermissionSeed;
  const codes = parsed.permissions.map((permission) => permission.key);
  const unique = new Set(codes);
  if (codes.length === 0) {
    throw new Error('permission-catalog.json must contain at least one permission');
  }
  if (unique.size !== codes.length) {
    throw new Error('permission-catalog.json contains duplicate keys');
  }
  const tuples = parsed.permissions.map(
    (permission) => `${permission.moduleKey}:${permission.resourceKey}:${permission.actionKey}`,
  );
  const uniqueTuples = new Set(tuples);
  if (uniqueTuples.size !== tuples.length) {
    throw new Error('permission-catalog.json contains duplicate module/resource/action tuples');
  }
  return parsed;
}

function writeBackendCatalog(seed: PermissionSeed): void {
  const permissions = seed.permissions.map((permission) => permission.key).sort();
  const permissionLines = permissions.map((permission) => `  '${permission}',`).join('\n');
  const content = `// Generated by scripts/gen-permissions.ts. Do not edit by hand.
export const PERMISSIONS = [
${permissionLines}
] as const;

export type Permission = (typeof PERMISSIONS)[number];
`;
  writeFileSync(backendCatalogPath, content);
}

function writeFrontendCatalog(seed: PermissionSeed): void {
  const entries: Array<[string, string]> = seed.permissions
    .filter((permission) => permission.routePattern?.startsWith('#!'))
    .map((permission) => [permission.routePattern ?? '', permission.key] as [string, string])
    .sort((left, right) => left[0].localeCompare(right[0]));
  const entryLines = entries
    .map(([pattern, permission]) => `  ['${pattern}', '${permission}'],`)
    .join('\n');
  const content = `// Generated by scripts/gen-permissions.ts. Do not edit by hand.
export const ROUTE_PERMISSION_MAP = [
${entryLines}
] as const;

export function permissionsForRoutePath(routePath: string): string[] {
  return ROUTE_PERMISSION_MAP.filter(([pattern]) => routeMatches(pattern, routePath)).map(
    ([, permission]) => permission,
  );
}

function routeMatches(pattern: string, routePath: string): boolean {
  const normalizedPattern = pattern.replace(/^#!/, '').replace(/\\/\\*\\*$/, '');
  const normalizedRoute = routePath.replace(/^#!/, '');
  return normalizedRoute.startsWith(normalizedPattern);
}
`;
  writeFileSync(frontendCatalogPath, content);
}

const seed = readSeed();
writeBackendCatalog(seed);
writeFrontendCatalog(seed);
